### ISSUE TITLE
how to use in my android app？

### ISSUE THREAD

**Issue by wl-tsui** [TrustWallet/trust-web3-provider#10]
How to use in my android  app？
How to combine with WebView components or other use?
Please give some ideas? 
thank you very much!!!

**Comment by vikmeup** [comment]
@wl-tsui take a look: https://github.com/TrustWallet/trust-web3-provider#android

**Comment by wl-tsui** [comment]
@vikmeup 
Thank you for your reply, but the documentation just says how to install it. How do I use it to access a dapp URL in code?

**Comment by vikmeup** [comment]
Take a look at this repo to integrate web3 view: https://github.com/TrustWallet/Web3View
