### ISSUE TITLE
this._request is not a function or undefined

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/trust-web3-provider#100]
"Uncaught (in promise) TypeError: (this || window.ethereum)._request is not a function", source: https://staking.dxsale.network/

**Comment by vikmeup** [comment]
> "Uncaught (in promise) TypeError: (this || window.ethereum)._request is not a function", source: https://staking.dxsale.network/

`_request` what is this magic function?

**Comment by hewigovens** [comment]
This is our internal helper method for both `request` and `sendAsync`, `this` is messed up somehow in some dapps
