### ISSUE TITLE
not receive any events in android

### ISSUE THREAD

**Issue by CoderWangP** [trustwallet/trust-web3-provider#104]
@hewigovens 
DevTools failed to load SourceMap: Could not load content for https://hyperdragons.alfakingdom.com/trust-min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
(index):703 Uncaught TypeError: Cannot set property 'setProvider' of undefined
    at (index):703
index.ecf9adcf.js:1 [FAILED][/get-bulletin-list]: System Error
(anonymous) @ index.ecf9adcf.js:1
sa.gif:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
index.ecf9adcf.js:1 [FAILED][/get-ave-eth-price]: Command Failed
(anonymous) @ index.ecf9adcf.js:1

**Comment by hewigovens** [comment]
can you share more details? which dapp, how to reproduce it, Trust app version

**Comment by CoderWangP** [comment]
> can you share more details? which dapp, how to reproduce it, Trust app version

dapp:https://hyperdragons.alfakingdom.com/
implementation 'com.github.TrustWallet:trust-web3-provider:0.3.9'
the init.js `
const addressHex = "%1$s";
const rpcURL = "%2$s";
const chainID = "%3$s";
function executeCallback (id, error, value) {
  Trust.executeCallback(id, error, value)
}
function onSignSuccessful(id, value) {
  Trust.executeCallback(id, null, value)
}
function onSignError(id, error) {
  Trust.executeCallback(id, error, null)
}
window.Trust.init(rpcURL, {
  getAccounts: function (cb) { cb(null, [addressHex]) },
  processTransaction: function (tx, cb){
    console.log('signing a transaction', tx)
    const { id = 8888 } = tx
    Trust.addCallback(id, cb)
    var gasLimit = tx.gasLimit || tx.gas || null;
    var gasPrice = tx.gasPrice || null;
    var data = tx.data || null;
    var nonce = tx.nonce || -1;
    trust.signTransaction(id, tx.to || null, tx.value, nonce, gasLimit, gasPrice, data);
  },
  signMessage: function (msgParams, cb) {
    const { data } = msgParams
    const { id = 8888 } = msgParams
    console.log("signing a message", msgParams)
    Trust.addCallback(id, cb)
    trust.signMessage(id, data);
  },
  signPersonalMessage: function (msgParams, cb) {
    const { data } = msgParams
    const { id = 8888 } = msgParams
    console.log("signing a personal message", msgParams)
    Trust.addCallback(id, cb)
    trust.signPersonalMessage(id, data);
  },
  signTypedMessage: function (msgParams, cb) {
    const { data } = msgParams
    const { id = 8888 } = msgParams
    Trust.addCallback(id, cb)
    trust.signTypedMessage(id, JSON.stringify(data))
  }
}, {
    address: addressHex,
    networkVersion: chainID
})
window.web3.setProvider = function () {
  console.debug('Trust Wallet - overrode web3.setProvider')
}
window.web3.eth.defaultAccount = addressHex
window.web3.version.getNetwork = function(cb) {
    cb(null, chainID)
}
window.web3.eth.getCoinbase = function(cb) {
    return cb(null, addressHex)
}`
i used trust-web3-provider in my own android app, but not receive any events，is there any android demo can run?

**Comment by hewigovens** [comment]
this dapp https://hyperdragons.alfakingdom.com/ doesn't even work with metamask

**Comment by CoderWangP** [comment]
> this dapp https://hyperdragons.alfakingdom.com/ doesn't even work with metamask

but i open it with trustwallet,it receives signMessage message

**Comment by hewigovens** [comment]
please take a look at iOS injected js code: https://github.com/trustwallet/trust-web3-provider/blob/master/ios/TrustWeb3Provider/WKUserScriptConfig.swift#L33, and latest provider version is `0.4.5` on github package

We don't have resources to implement an android demo, feel free to contribute one

for testing, you could try https://js-eth-sign.surge.sh

**Comment by CoderWangP** [comment]
> please take a look at iOS injected js code: https://github.com/trustwallet/trust-web3-provider/blob/master/ios/TrustWeb3Provider/WKUserScriptConfig.swift#L33, and latest provider version is `0.4.5` on github package
> 
> We don't have resources to implement an android demo, feel free to contribute one
> 
> for testing, you could try https://js-eth-sign.surge.sh

i change to 0.4.5,but it miss trust-min.js raw file
  implementation 'com.github.TrustWallet:trust-web3-provider:0.4.5'

**Comment by CoderWangP** [comment]
Uncaught (in promise) TypeError: Cannot read property 'messageHandlers' of undefined
    at TrustWeb3Provider.value (hyperdragons.alfakingdom.com/:656)
    at TrustWeb3Provider.value (hyperdragons.alfakingdom.com/:656)
    at hyperdragons.alfakingdom.com/:656
    at new Promise (<anonymous>)
    at TrustWeb3Provider.value (hyperdragons.alfakingdom.com/:656)
    at TrustWeb3Provider.value (hyperdragons.alfakingdom.com/:656)
    at TrustWeb3Provider.value (hyperdragons.alfakingdom.com/:656)
    at B (index.ecf9adcf.js:1)
    at Module.4cae (index.ecf9adcf.js:1)
    at c (index.ecf9adcf.js:1)

i injected js code like iOS demo ，but got this error

**Comment by hewigovens** [comment]
Android webview doesn't have `window.webkit.messageHandlers`, you need to mock it or override it, one test example: https://github.com/trustwallet/trust-web3-provider/blob/master/src/tests/test.js#L113

**Comment by CoderWangP** [comment]
`js`
var config = {
    address: "%1$s",
    chainId: "%2$s",
    rpcUrl: "%3$s"
};
const provider = new window.Trust(config);
provider.isDebug = true;
window.ethereum = provider;
window.web3 = new window.Web3(provider);
window.web3.eth.defaultAccount = config.address;

window.chrome = {webstore: {}};

window.web3.setProvider = function () {
  console.debug('Trust Wallet - overrode web3.setProvider')
}

window.webkit.messageHandlers = {
    signMessage: {
      postMessage: (message) => {
        Trust.postMessage(message)
      }
    }
    requestAccounts:{
      postMessage: (message) => {
        Trust.postMessage(message)
      }
    }
};

 https://js-eth-sign.surge.sh
the injected js is above,but when i click eht_sign get the error:

bundle.js:28 Uncaught ReferenceError: web3 is not defined
    at HTMLButtonElement.<anonymous> (bundle.js:28) @hewigovens

**Comment by hewigovens** [comment]
what's `Trust.postMessage(message)`? you should handle message singing inside your app. `web3` is not defined means you didn't inject js properly, there might be some js error

**Comment by CoderWangP** [comment]
> what's `Trust.postMessage(message)`? you should handle message singing inside your app. `web3` is not defined means you didn't inject js properly, there might be some js error

thanks very much,it has been solved.

**Comment by hewigovens** [comment]
great, would you mind to contribute an android demo?

**Comment by CoderWangP** [comment]
> great, would you mind to contribute an android demo?

I am very happy to provide a demo after finishing the current project.

**Comment by VliceZ** [comment]
@CoderWangP 遇到和你一样的问题，搞了两天没解决，能否加上你的国内联系方式，微信或qq

**Comment by vtproduction** [comment]
@CoderWangP could you please give some example of how to use this lib in Android, thanks!

**Comment by QuincySx** [comment]
Thank you for your discussion. It worked.
