### ISSUE TITLE
Flutter Ios injection failed

### ISSUE THREAD

**Issue by lonerchen** [trustwallet/trust-web3-provider#107]
I tried to inject trust.js on the Flutter side, and it worked normally on the Android side device, and the following message was reported on the IOS side.
`
javaScript string was: 'parcelRequire=function(e,r,t,n){var i,o="function"==typeof parcelRequire&&parcelRequire ... ...
Error Domain=WKErrorDomain Code=5 "JavaScript execution returned a result of an unsupported type" UserInfo={NSLocalizedDescription=JavaScript execution returned a result of an unsupported type}
`
project use `webview_flutter: ^1.0.5` Ios is backed by a ‘WKWebView ’

This problem has troubled me for a long time, I hope to help solve it, thank you

**Comment by hewigovens** [comment]
Can you share your sample code? It must be something wrong in flutter webview wrapper or not configured correctly , it does work in iOS WKWebView

**Comment by lonerchen** [comment]
this is my Flutter code.
`
        child: WebView(
//              initialUrl: "http://192.168.1.24:3000/",
          initialUrl: "https://pandora.vpntube.app/build/index.html#/swap",
          javascriptMode: JavascriptMode.unrestricted,
          userAgent: "random",
          onWebViewCreated: (controller)async{
            _myController = controller;
          },
//          javascriptChannels: <JavascriptChannel>{
//            signTransaction(context),
//            signMessage(context),
//            signPersonalMessage(context),
//            signTypedMessage(context),
//            eth_signTypedData_v3(context),
//            requestAccounts(context),
//            eth_requestAccounts(context),
//          },
          onPageFinished: (str)async{
            String js2 = await rootBundle.loadString("assets/trust.js");
            String js = await rootBundle.loadString("assets/init.js");
            await _myController.evaluateJavascript(js2).then((value){
              print(value);
            });
//          await _myController.evaluateJavascript(paramString).then((value){
//            print(value);
//          });
          },
        ),

`

**Comment by lonerchen** [comment]
I found a related solution, but I don’t know what the problem is. It may be a bug in Flutter
https://github.com/flutter/flutter/issues/66318
