### ISSUE TITLE
window.ethereum is undefined in https

### ISSUE THREAD

**Issue by levx-io** [trustwallet/trust-web3-provider#108]
When you visiti https://lite.sushiswap.fi/ with TrustWallet, `window.ethereum` is `undefined`.

But if you clone `https://github.com/sushiswap/sushiswap.github.io`, which is the same code as https://lite.sushiswap.fi/, and run a http server instead of https, it works perfectly.

I've configured different settings for many hours but I can't seem to find out the reason except https thing.

**Comment by hewigovens** [comment]
What's your app version and OS system? Have you tried VPN (sushiswap.fi is blocked in China)? It's fine on Trust iOS for me.

**Comment by levx-io** [comment]
@hewigovens Can you access to https://lite.sushiswap.fi/ and use it perfectly?
I'm not using any vpn nor I'm not in china.

HTML and js assets load successfully but only `window.ethereum` is not injected.

**Comment by vikmeup** [comment]
If you have an issue on Android, can you disable service workers? it will fix an issue

<img width="753" alt="Screen Shot 2020-11-10 at 1 08 28 AM" src="https://user-images.githubusercontent.com/1641795/98652972-42510200-22f1-11eb-917e-cb3f824c62f2.png">

**Comment by hewigovens** [comment]
@levx-io I haven't tested everything, it connected and window.ethereum was there

**Comment by levx-io** [comment]
Turning off server workers solved issues. Thanks @vikmeup
