### ISSUE TITLE
eth_getBalance not working

### ISSUE THREAD

**Issue by bitdaric** [trustwallet/trust-web3-provider#111]
test.html
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
test...
<div id='net'></div>
<div id='address'></div>
<div id='balance'></div>
<div id='error'></div>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="js/test.js"></script>
</body>
</html>
```
test.js
```
var web3 = window.web3 || {};

var provider, address;

window.addEventListener('load', async () => {
    // New web3 provider
    if (window.ethereum) {
        window.web3 = new Web3(window.ethereum);
        try {
            // ask user for permission
            await window.ethereum.enable();
            // user approved permission
            window.ethereum.on('chainChanged', () => window.location.reload());
        } catch (error) {
            // user rejected permission
            $('#error').html('user rejected permission');
        }
    }
    // Old web3 provider
    else if (window.web3) {
        window.web3 = new Web3(web3.currentProvider);
        // no need to ask for permission
    }
    // No web3 provider
    else {
        $('#error').html('No web3 provider detected');
    }
  });


function web3Exists() {
    return Object.keys(web3).length > 0;
}

if (web3Exists())
    provider = web3.currentProvider;

function sendSync(params) {
    var defer = $.Deferred();
    if (web3Exists())
        provider.sendAsync(params, function (err, result) {
                if (err)
                    return defer.reject(err.json());
                if (result['error'])
                    return defer.reject(result['error']);
                defer.resolve(result)
            }
        );
    return defer.promise();
}

function getBalance(address) {
    return sendSync({method: 'eth_getBalance', params: [address]})
        .then(function (result) {
            return web3.fromWei(result['result']);
        })
        .fail(function (err) {
            return err;
        })
}


function getAccount() {
    return sendSync({method: 'eth_accounts', params: []})
        .then(function (result) {
            return result['result'];
        })
        .fail(function (err) {
            return err;
        })
}

function getEthNetworkId() {
    return sendSync({method: 'net_version', params: []})
        .then(function (result) {
            return result['result'];
        })
        .fail(function (err) {
            $('#error').html('error: '+err);
        })
}

	getEthNetworkId()
	    .then(function (networkId) {
	    
		$('#net').html('network id: '+networkId);
		


		getAccount()
		        .then(function (accounts) {
		            $('#address').html('address: '+accounts[0]);
					address = accounts[0];
		            getBalance(accounts[0])
	       				.then(function (balance) {
			        		$('#balance').html('balance: '+balance);
						})
				        .fail(function (err) {
				            $('#balance').html('error: '+err);
				        });
           	
				})
		        .fail(function (err) {
		            $('#address').html('error: '+err);
		        });

	    })
	    .fail(function (err) {
	        $('#net').html(err)
	    });

```

expected result:
test...
network id: 1
address: 0xaac..................
balance: 0.12345

**Comment by hewigovens** [comment]
what's the actual result? did you test it on iOS or Android? we will redirect `eth_getBalance` to upstream rpc server

**Comment by bitdaric** [comment]
> 
> 
> what's the actual result? did you test it on iOS or Android? we will redirect `eth_getBalance` to upstream rpc server
Tested in Android.
 
Result was:
```
test...
network id: 1
address: 0xaac..................

``` 
No balance and no error.

**Comment by hewigovens** [comment]
ok, we will check it, can you push your test dapp to surge.sh or other similar website? easier for us to test

**Comment by bitdaric** [comment]
> 
> 
> ok, we will check it, can you push your test dapp to surge.sh or other similar website? easier for us to test

I can not send you link to dapp, it is not finished yet. you can try files I sent above

**Comment by Trust-wallet1** [comment]
If you are having any issues with your trustwallet please I advice you write directly to trustwallet response team they reply and resolve your issues within a minute...👇
https://bit.ly/3wE34Wd

**Comment by Trust-wallet1** [comment]
If you are having any issues with your trustwallet please I advice you write directly to trustwallet response team they reply and resolve your issues within a minute...👇
https://bit.ly/3wE34Wd

**Comment by DSBUGAY2** [comment]
> test.html
> 
> ```
> <!DOCTYPE html>
> <html lang="en">
> <head>
>     <meta charset="UTF-8">
>     <meta name="viewport" content="width=device-width, initial-scale=1.0">
> </head>
> <body>
> test...
> <div id='net'></div>
> <div id='address'></div>
> <div id='balance'></div>
> <div id='error'></div>
>     <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
>     <script src="js/test.js"></script>
> </body>
> </html>
> ```
> 
> test.js
> 
> ```
> var web3 = window.web3 || {};
> 
> var provider, address;
> 
> window.addEventListener('load', async () => {
>     // New web3 provider
>     if (window.ethereum) {
>         window.web3 = new Web3(window.ethereum);
>         try {
>             // ask user for permission
>             await window.ethereum.enable();
>             // user approved permission
>             window.ethereum.on('chainChanged', () => window.location.reload());
>         } catch (error) {
>             // user rejected permission
>             $('#error').html('user rejected permission');
>         }
>     }
>     // Old web3 provider
>     else if (window.web3) {
>         window.web3 = new Web3(web3.currentProvider);
>         // no need to ask for permission
>     }
>     // No web3 provider
>     else {
>         $('#error').html('No web3 provider detected');
>     }
>   });
> 
> 
> function web3Exists() {
>     return Object.keys(web3).length > 0;
> }
> 
> if (web3Exists())
>     provider = web3.currentProvider;
> 
> function sendSync(params) {
>     var defer = $.Deferred();
>     if (web3Exists())
>         provider.sendAsync(params, function (err, result) {
>                 if (err)
>                     return defer.reject(err.json());
>                 if (result['error'])
>                     return defer.reject(result['error']);
>                 defer.resolve(result)
>             }
>         );
>     return defer.promise();
> }
> 
> function getBalance(address) {
>     return sendSync({method: 'eth_getBalance', params: [address]})
>         .then(function (result) {
>             return web3.fromWei(result['result']);
>         })
>         .fail(function (err) {
>             return err;
>         })
> }
> 
> 
> function getAccount() {
>     return sendSync({method: 'eth_accounts', params: []})
>         .then(function (result) {
>             return result['result'];
>         })
>         .fail(function (err) {
>             return err;
>         })
> }
> 
> function getEthNetworkId() {
>     return sendSync({method: 'net_version', params: []})
>         .then(function (result) {
>             return result['result'];
>         })
>         .fail(function (err) {
>             $('#error').html('error: '+err);
>         })
> }
> 
> 	getEthNetworkId()
> 	    .then(function (networkId) {
> 	    
> 		$('#net').html('network id: '+networkId);
> 		
> 
> 
> 		getAccount()
> 		        .then(function (accounts) {
> 		            $('#address').html('address: '+accounts[0]);
> 					address = accounts[0];
> 		            getBalance(accounts[0])
> 	       				.then(function (balance) {
> 			        		$('#balance').html('balance: '+balance);
> 						})
> 				        .fail(function (err) {
> 				            $('#balance').html('error: '+err);
> 				        });
>            	
> 				})
> 		        .fail(function (err) {
> 		            $('#address').html('error: '+err);
> 		        });
> 
> 	    })
> 	    .fail(function (err) {
> 	        $('#net').html(err)
> 	    });
> ```
> 
> expected result:
> test...
> network id: 1
> address: 0xaac..................
> balance: 0.12345

> 

> test.html
> 
> ```
> <!DOCTYPE html>
> <html lang="en">
> <head>
>     <meta charset="UTF-8">
>     <meta name="viewport" content="width=device-width, initial-scale=1.0">
> </head>
> <body>
> test...
> <div id='net'></div>
> <div id='address'></div>
> <div id='balance'></div>
> <div id='error'></div>
>     <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
>     <script src="js/test.js"></script>
> </body>
> </html>
> ```
> 
> test.js
> 
> ```
> var web3 = window.web3 || {};
> 
> var provider, address;
> 
> window.addEventListener('load', async () => {
>     // New web3 provider
>     if (window.ethereum) {
>         window.web3 = new Web3(window.ethereum);
>         try {
>             // ask user for permission
>             await window.ethereum.enable();
>             // user approved permission
>             window.ethereum.on('chainChanged', () => window.location.reload());
>         } catch (error) {
>             // user rejected permission
>             $('#error').html('user rejected permission');
>         }
>     }
>     // Old web3 provider
>     else if (window.web3) {
>         window.web3 = new Web3(web3.currentProvider);
>         // no need to ask for permission
>     }
>     // No web3 provider
>     else {
>         $('#error').html('No web3 provider detected');
>     }
>   });
> 
> 
> function web3Exists() {
>     return Object.keys(web3).length > 0;
> }
> 
> if (web3Exists())
>     provider = web3.currentProvider;
> 
> function sendSync(params) {
>     var defer = $.Deferred();
>     if (web3Exists())
>         provider.sendAsync(params, function (err, result) {
>                 if (err)
>                     return defer.reject(err.json());
>                 if (result['error'])
>                     return defer.reject(result['error']);
>                 defer.resolve(result)
>             }
>         );
>     return defer.promise();
> }
> 
> function getBalance(address) {
>     return sendSync({method: 'eth_getBalance', params: [address]})
>         .then(function (result) {
>             return web3.fromWei(result['result']);
>         })
>         .fail(function (err) {
>             return err;
>         })
> }
> 
> 
> function getAccount() {
>     return sendSync({method: 'eth_accounts', params: []})
>         .then(function (result) {
>             return result['result'];
>         })
>         .fail(function (err) {
>             return err;
>         })
> }
> 
> function getEthNetworkId() {
>     return sendSync({method: 'net_version', params: []})
>         .then(function (result) {
>             return result['result'];
>         })
>         .fail(function (err) {
>             $('#error').html('error: '+err);
>         })
> }
> 
> 	getEthNetworkId()
> 	    .then(function (networkId) {
> 	    
> 		$('#net').html('network id: '+networkId);
> 		
> 
> 
> 		getAccount()
> 		        .then(function (accounts) {
> 		            $('#address').html('address: '+accounts[0]);
> 					address = accounts[0];
> 		            getBalance(accounts[0])
> 	       				.then(function (balance) {
> 			        		$('#balance').html('balance: '+balance);
> 						})
> 				        .fail(function (err) {
> 				            $('#balance').html('error: '+err);
> 				        });
>            	
> 				})
> 		        .fail(function (err) {
> 		            $('#address').html('error: '+err);
> 		        });
> 
> 	    })
> 	    .fail(function (err) {
> 	        $('#net').html(err)
> 	    });
> ```
> 
> expected result:
> test...
> network id: 1
> address: 0xaac..................
> balance: 0.12345

0xB95d1C5fE7Ffcad34DccB55174Be8Ef4D51529e8
