### ISSUE TITLE
iOS 内置的测试DApp无法正常运行

### ISSUE THREAD

**Issue by CYC666** [trustwallet/trust-web3-provider#112]
IOS built-in test DAPP does not work properly

iOSdemo运行起来后，点击里面DApp的按钮，无法正常获取钱包信息，无法响应签名事件，所有操作都无法响应，请回复请回复！

**Comment by hewigovens** [comment]
can you share more details? what is the built in dapp? were you saying this demo app? https://github.com/trustwallet/trust-web3-provider/tree/master/ios

**Comment by wkn66** [comment]
我也遇到同样的问题  下载了iosdemo并且运行后，http://js-eth-sign.surge.sh/这个网页内的所有按钮都无法响应
