### ISSUE TITLE
Some dapps can't connect to addresses，eg: https://defil.org/

### ISSUE THREAD

**Issue by togiter** [trustwallet/trust-web3-provider#118]
Want to access https://defil.org/，The address request was called with no result。
Other wallets can be connected，such as： imtoken, metamask
<img width="343" alt="WeChatde6cf5507091434e4d9075ebe5ce239f" src="https://user-images.githubusercontent.com/18685332/103642044-94c73b80-4f8d-11eb-94c4-02922235c993.png">
<img width="332" alt="WeChat2094992e7e439154749fb70ce1c8e5f1" src="https://user-images.githubusercontent.com/18685332/103642762-9cd3ab00-4f8e-11eb-8352-a2d83a21eb1e.png">

<img width="1272" alt="WeChat5de3d3f53256916e278902199b4eeb2a" src="https://user-images.githubusercontent.com/18685332/103642781-a4934f80-4f8e-11eb-84f0-ce722c003b95.png">

**Comment by hewigovens** [comment]
do you have web3 sample code like defil.org? from the log, trust provider did send the response but callback not fired

**Comment by togiter** [comment]
I didn't. this is the official application of filecoin。But there is no problem in using imtoken and metamask

**Comment by togiter** [comment]
No, this is a third-party DAPP, but both imtoken and metask can be used successfully。

**Comment by hewigovens** [comment]
we need more detail information to debug it

**Comment by search110** [comment]
@togiter  Is there any response or is it okay to obtain the address authorization? It seems that I have encountered similar problems when using other DAPPs.
