### ISSUE TITLE
Can't select swap token when using a rpcUrl( "https://ropsten.infura.io/v3/38511353a31343fcb68ca6231e6e0427")

### ISSUE THREAD

**Issue by suckerSlayer** [trustwallet/trust-web3-provider#119]
When use rpcUrl( 'https://ropsten.infura.io/v3/38511353a31343fcb68ca6231e6e0427') the destination token list can't show up, but only there is a ETH token in it. 
My wallet address is '0x36909082f08b82ccc8d95e595f7b0bc5a102325d'

**Comment by hewigovens** [comment]
which dapp?

**Comment by suckerSlayer** [comment]
uniswap
---原始邮件---
发件人:&quot;hewigovens&quot;<notifications@github.com&gt;
发送时间:2021年1月7日 星期四 下午8:17
收件人:&quot;trustwallet/trust-web3-provider&quot;<trust-web3-provider@noreply.github.com&gt;
抄送:&quot;suckerSlayer&quot;<978466658@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;
主题:Re: [trustwallet/trust-web3-provider] Can&#39;t select swap token when using a rpcUrl( &quot;https://ropsten.infura.io/v3/38511353a31343fcb68ca6231e6e0427&quot;) (#119)



which&nbsp;dapp?

&mdash;
You&nbsp;are&nbsp;receiving&nbsp;this&nbsp;because&nbsp;you&nbsp;authored&nbsp;the&nbsp;thread.
Reply&nbsp;to&nbsp;this&nbsp;email&nbsp;directly,view&nbsp;it&nbsp;on&nbsp;GitHub,&nbsp;orunsubscribe.
