### ISSUE TITLE
web3: getPastEvents not working for block filters larger than 1mln blocks

### ISSUE THREAD

**Issue by crosstec** [trustwallet/trust-web3-provider#121]
**Describe the bug**
If trying to filter from block 0 to latest, an error is thrown and no filter results are returned.

(Unfortunately, I cannot tell the exact error as Trust Wallet doesn't allow WebView debugging)

**To Reproduce**
Use a filter like this

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by hewigovens** [comment]
we don't support filter methods

**Comment by hewigovens** [comment]
duplicated with https://github.com/trustwallet/trust-web3-provider/issues/122

**Comment by crosstec** [comment]
well, no problem. then we will advice people to keep using metamask.

**Comment by vikmeup** [comment]
You just need to use your own provider to fetch data from the network. 

Only use injected provider to sign transactions. 

This is the best practices for building web3 applications
