### ISSUE TITLE
Show Trust icon and name on mycrypto.com

### ISSUE THREAD

**Issue by hewigovens** [TrustWallet/trust-web3-provider#13]
https://support.mycrypto.com/contributor-info/adding-support-for-web3-wallet.html

**Comment by vikmeup** [comment]
@hewigovens should this be closed?

**Comment by hewigovens** [comment]
leave it for tracking purpose, I will submit a PR to MyCrypto anyway.

**Comment by vikmeup** [comment]
@hewigovens released now, should we close it?
