### ISSUE TITLE
Support `eth_getEncryptionPublicKey`

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/trust-web3-provider#135]

**Comment by hewigovens** [comment]
we can leverage `eth-sig-util`

**Comment by Trust-wallet1** [comment]
If you are having any issues with your trustwallet please I advice you write directly to trustwallet response team they reply and resolve your issues within a minute...👇
https://bit.ly/3wE34Wd

**Comment by hewigovens** [comment]
close for now

**Comment by Sgoldik** [comment]
Any updates? eth_getEncryptionPublicKey and eth_decrypt functions would be useful for my DApp marketplace.

**Comment by hewigovens** [comment]
@Sgoldik take a look at https://medium.com/metamask/metamask-api-method-deprecation-2b0564a84686
