### ISSUE TITLE
What is the right way to use web3 inside dApp in TrustWallet?

### ISSUE THREAD

**Issue by frimuchkov** [trustwallet/trust-web3-provider#141]
Hi!

I try to run the app inside TrustWallet and something goes wrong.

I use `useWeb3React` and call activate with injected connector:
```
import { InjectedConnector } from '@web3-react/injected-connector';
import { useWeb3React } from '@web3-react/core';

export const injected = new InjectedConnector({
  supportedChainIds: [1]
});

const { activate } = useWeb3React();
await activate(injected, undefined, true);
```
and get the next error:
`
Trust does not support calling undefined synchronously without a callback. Please provide a callback parameter to call undefined asynchronously.
`

**Comment by hewigovens** [comment]
what underlying jsonrpc in `activate` call? the parameter looks weird to me `undefined `?

**Comment by frimuchkov** [comment]
> what underlying jsonrpc in `activate` call? the parameter looks weird to me `undefined `?

It's ok, just call without a callback for an error
I've loved my problem, looks like this error is acceptable
