### ISSUE TITLE
some dapps can't connect to addresses，eg: https://uniswap.token.im/#/pool?locale=zh-CN

### ISSUE THREAD

**Issue by search110** [trustwallet/trust-web3-provider#144]
After calling uniswap's DAPP authorization to obtain the address, after executing let script = String(format: "window.ethereum.sendResponse(%ld, [%@])", id, array.joined(separator: ",")) , There is no callback or response, authorization seems to be unsuccessful
<img width="806" alt="截屏2021-05-06 16 28 13" src="https://user-images.githubusercontent.com/16936747/117268976-706f6300-ae8a-11eb-9453-cdf6ab830b26.png">
<img width="322" alt="截屏2021-05-06 16 44 36" src="https://user-images.githubusercontent.com/16936747/117268987-7402ea00-ae8a-11eb-80e5-8c54f5416b9c.png">

**Comment by hewigovens** [comment]
take a look at the sample code: https://github.com/trustwallet/trust-web3-provider/blob/master/ios/TrustWeb3Provider/DAppWebViewController.swift#L131

**Comment by search110** [comment]
> take a look at the sample code: https://github.com/trustwallet/trust-web3-provider/blob/master/ios/TrustWeb3Provider/DAppWebViewController.swift#L131

I am running the sample code of the current project, I don’t know if you have passed the test

**Comment by search110** [comment]
> > take a look at the sample code: https://github.com/trustwallet/trust-web3-provider/blob/master/ios/TrustWeb3Provider/DAppWebViewController.swift#L131
> 
> I am running the sample code of the current project, I don’t know if you have passed the test

<img width="1207" alt="截屏2021-05-07 21 55 25" src="https://user-images.githubusercontent.com/16936747/117460389-0d132d00-af7f-11eb-9b8f-bb5ec2bc02e2.png">
Please reply me if the author sees it, because this is too important for me

**Comment by WhiteCjy** [comment]
这个问题你解决了吗

**Comment by search110** [comment]
解决了发自我的iPhone------------------ Original ------------------From: WhiteCjy  ***@***.***>Date: Mon,Aug 16,2021 4:07 PMTo: trustwallet/trust-web3-provider ***@***.***>Cc: jackcao ***@***.***>, Author ***@***.***>Subject: Re: [trustwallet/trust-web3-provider] some dapps can't connect to addresses，eg: https://uniswap.token.im/#/pool?locale=zh-CN (#144)
这个问题你解决了吗

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/trustwallet/trust-web3-provider/issues/144#issuecomment-899310473",
"url": "https://github.com/trustwallet/trust-web3-provider/issues/144#issuecomment-899310473",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by CubeFeng** [comment]
> 解决了发自我的iPhone------------------ Original ------------------From: WhiteCjy ***@***.***>Date: Mon,Aug 16,2021 4:07 PMTo: trustwallet/trust-web3-provider ***@***.***>Cc: jackcao ***@***.***>, Author ***@***.***>Subject: Re: [trustwallet/trust-web3-provider] some dapps can't connect to addresses，eg: https://uniswap.token.im/#/pool?locale=zh-CN (#144) 这个问题你解决了吗 —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. [ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "[#144 (comment)](https://github.com/trustwallet/trust-web3-provider/issues/144#issuecomment-899310473)", "url": "[#144 (comment)](https://github.com/trustwallet/trust-web3-provider/issues/144#issuecomment-899310473)", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

怎么解决的？
