### ISSUE TITLE
signTypedData_v4 support

### ISSUE THREAD

**Issue by anxolin** [trustwallet/trust-web3-provider#148]
Hi, how should we debug in IOS?

So I'm having issues signing offchain transactions in this dapp http://cowswap.exchange

I tried to follow the instructions in https://developer.trustwallet.com/dapps/debugging on how to debug for IOS, but there's very little details.

The instructions points to this project. I don't see any instruction to follow, and I'm not an IOS developer, so I feel a bit lost here. 

I tried to open the xCode project in this repository, and it fails building:
![image](https://user-images.githubusercontent.com/2352112/118025851-92705600-b360-11eb-8a09-9694dd4dc290.png)

Can I get some instructions or help to see why the Dapp is not working?
It works for most other wallets, so I was trying to understand why not in Trust.

**Comment by hewigovens** [comment]
I can connect but see a few errors in the console, do you see any error? how to reproduce?

![Screen Shot 2021-05-13 at 12 27 22](https://user-images.githubusercontent.com/360470/118073384-aeb6d600-b3e6-11eb-94e6-a2d0f18218d0.png)
![Screen Shot 2021-05-13 at 12 27 03](https://user-images.githubusercontent.com/360470/118073377-ab234f00-b3e6-11eb-95d8-ae3845c036b3.png)

**Comment by anxolin** [comment]
Hi, yes, the issue happens with the offchain signing of transactions.

We used `signTypedData_v4` (see https://docs.metamask.io/guide/signing-data.html#signing-data-with-metamask for context).


For trying this out, you can try to do a SWAP:
1. Connect (you can use Mainnet, Rinkeby or xDAI networks)
2. Select a token pair. i.e DAI / USDC
3. Approve the sell token (enable for trading)
4. Swap ---> `This will ask you to sign an off-chain transaction` using `signTypedData_v4`, which is what is failing.

I can send you tokens to a Rinkeby address if it helps to reproduce.

**Comment by hewigovens** [comment]
Hi, we will consider adding `signTypedData_v4` support, currently it only supports v3

**Comment by anxolin** [comment]
Thanks! Please, yes I think it would be very nice if Trust wallet can also do this kind of transaction signing.

**Comment by anxolin** [comment]
Hei @hewigovens I think there's a different issue too.

CowSwap also default back to v3 and `eth_sign`. You can see how this URL works in Android, but not IOS Trust Wallet: https://pr576--gpswapui.review.gnosisdev.com/#/swap

**Comment by hewigovens** [comment]
Ok, will take a look

**Comment by hewigovens** [comment]
we have a working pr here: https://github.com/trustwallet/trust-web3-provider/pull/149
