### ISSUE TITLE
Issue injecting with Flutter, not recieving any callbacks except requestAccounts

### ISSUE THREAD

**Issue by AyushBherwani1998** [trustwallet/trust-web3-provider#150]
While injecting with Flutter, I do receive callbacks for `requestAccounts` and it works fine. On Uniswap or ShushiSwap when I try to swap any token it doesn't give me any callback and fails with message provider is not ready.

Any ideas what I might be doing wrong?

**Comment by hewigovens** [comment]
please checkout the ios or android demo, you need to set address explicitly: https://github.com/trustwallet/trust-web3-provider/blob/master/ios/TrustWeb3Provider/DAppWebViewController.swift#L142
