### ISSUE TITLE
error  callback id

### ISSUE THREAD

**Issue by WTree** [trustwallet/trust-web3-provider#154]
when use sign Transfer,call back toDapp will show
callback id: 1622964377516 not found"

**Comment by han-jiang** [comment]
Is the same problem.
How is solved the problem？

**Comment by hewigovens** [comment]
it's just a warning, do you have iframe in your dapp?

**Comment by han-jiang** [comment]
dapp not have iframe

**Comment by WhiteCjy** [comment]
Is the same problem.
How is solved the problem？

**Comment by HungNguyenBao** [comment]
Same problem. Does anyone solved this?

**Comment by water125555** [comment]
664adf3f29d3235b673616d7cd78742c8daac886c9d698f07d8b5439a9b8763a
