### ISSUE TITLE
Can't find variable: web3

### ISSUE THREAD

**Issue by EvnLi** [trustwallet/trust-web3-provider#156]
ReferenceError: Can't find variable: web3
/bundle.js:173:18 https://js-eth-sign.surge.sh/bundle.js:173:18
ReferenceError: Can't find variable: web3
/bundle.js:173:18 https://js-eth-sign.surge.sh/bundle.js:173:18

**Comment by hewigovens** [comment]
Do you have more contexts? it looks like it's not injected correctly
