### ISSUE TITLE
Not being able to detect window.ethereum for a non-https connection

### ISSUE THREAD

**Issue by abhisareen2002** [trustwallet/trust-web3-provider#158]
I have a development server, run locally, so I just head over to my dapp link and even though it's working perfectly when the page is on a HTTPS connection, it does not run on the local connection, that is not encrypted. window.ethereum is undefined and wallet does not inject JS. Is there something I need to specifically do? Or do I need to again and again, upload it onto a live server with SSL to test it?
I'm using BinanceChain, but it's not working for ethereum either...

**Comment by TN8ru5omyg2kf94j6SH7DyEENPJkFY2ftZ** [comment]
Abc

**Comment by hewigovens** [comment]
Were you testing on android? for security reason you should always use https, service like https://vercel.com/ can help you easy deploying
