### ISSUE TITLE
Support for EIP712 typed data signing

### ISSUE THREAD

**Issue by bonustrack** [trustwallet/trust-web3-provider#162]
**Describe the bug**
Signing EIP712 message is failing from Trust Wallet browser on Snapshot.org.

**To Reproduce**
- Use your Trust Wallet browser to navigate on https://demo.snapshot.org/#/fabien.eth/proposal/QmdPbp9HiGtun5PCV3yp87a8YJvsZJPRwmQhFiHAPZXAgh
- Log in (click on "Connect wallet" then select "Trust Wallet")
- Select "Yes" or "No" in the "Cast your vote" block then click "Vote"
- Click "Vote" again to confirm your vote
- Vote will fail before user is triggered to sign the message

**Expected behavior**
Trust Wallet should trigger user to sign the EIP712 message.

**Additional context**
If I log in with WalletConnect from Trust Wallet app the signing is working fine.

**Comment by hewigovens** [comment]
Tried latest code in demo app, seems working, @vcoolish will integrate latest provider into android app, should be fixed soon
![Simulator Screen Shot - iPhone 12 mini - 2021-07-12 at 20 51 59](https://user-images.githubusercontent.com/360470/125290623-7b97b100-e35b-11eb-9cf5-e5a64ceb86ab.png)

**Comment by vcoolish** [comment]
Version with updated web3 provider will be out this week

**Comment by bonustrack** [comment]
@vcoolish @hewigovens Great to hear! Thanks for the quick answer. Will it work for the array types like `string[]` or `uint64[]` (introduced in v4 of EIP712). You can test array type by voting on here: https://demo.snapshot.org/#/fabien.eth/proposal/QmNueeqwrnFPpiQkv8pFeSe8JPKJcdXXvMsHu5ecjM28j3 Currently it's also not working on my device (Android).

**Comment by hewigovens** [comment]
@bonustrack yes, it should work too, also will support v4 in native code (Wallet Connect)

**Comment by hewigovens** [comment]
![Simulator Screen Shot - iPhone 12 mini - 2021-07-13 at 06 31 14](https://user-images.githubusercontent.com/360470/125363866-6303b700-e3ac-11eb-850f-bc680dbe700e.png)

**Comment by bonustrack** [comment]
Awesome thanks!

**Comment by vcoolish** [comment]
The webpage is not loading on android
"Uncaught TypeError: Object.fromEntries is not a function"

**Comment by bonustrack** [comment]
@vcoolish Can you confirm you are trying to open this page: https://demo.snapshot.org/#/fabien.eth/proposal/QmNueeqwrnFPpiQkv8pFeSe8JPKJcdXXvMsHu5ecjM28j3 ?
I can't reproduce the error, for me the page load fine.

**Comment by vcoolish** [comment]
<img width="575" alt="Снимок экрана 2021-07-14 в 14 35 29" src="https://user-images.githubusercontent.com/32914239/125615556-0cf8a7c6-1b47-4870-b520-094b09c44b0d.png">

works on android R, but didn't load on Android API 24

**Comment by hewigovens** [comment]
should be supported in latest Android app
