### ISSUE TITLE
personal_sign method not work

### ISSUE THREAD

**Issue by MirrorZyb** [trustwallet/trust-web3-provider#163]
Throw an exception in the messageToBuffer method  
The test step: open [polygon web wallet](https://wallet.matic.network/login/ )   click metaMask(ETH chain)，The authorization alert could not be called

**Comment by hewigovens** [comment]
could you please share detail exception log?

**Comment by MirrorZyb** [comment]
> could you please share detail ex
`TypeError: Invalid hex string`  The original string is：

Hi there from Polygon Wallet! Sign this message to prove you have access to this wallet and we'll log you in. This won't cost you any Ether.

To stop hackers using your wallet, here's a unique message ID they can't guess: bbe70577-fbd1-4e4f-b8b3-0928964ab5e0

Timestamp: 1626925528

**Comment by hewigovens** [comment]
Ah I see, are you using Trust Android or your own app? what's the app version? usually message in `personal_sign` should be hex string

**Comment by MirrorZyb** [comment]
> Ah I see, are you using Trust Android or your own app? what's the app version? usually message in `personal_sign` should be hex string

SDK is the latest version. I understand that hex string is required, but I can't ask DApp to modify the code. After all, MetaMask and TokenPocket are supported, and Trust Wallet of App Store is OK。

Can you give me some suggestions ? thank you

**Comment by hewigovens** [comment]
You meant Google Play? Trust iOS has removed DApp browser

take a look at `personal_sign`, it handles two cases (hex / non hex)
```js
  personal_sign(payload) {
    const message = payload.params[0];
    const buffer = Utils.messageToBuffer(message);
    if (buffer.length === 0) {
      // hex it
      const hex = Utils.bufferToHex(message);
      this.postMessage("signPersonalMessage", payload.id, { data: hex });
    } else {
      this.postMessage("signPersonalMessage", payload.id, { data: message });
    }
  }
```

**Comment by MirrorZyb** [comment]
> ```js
> messageToBuffer
> ```


I accessed it through WalletConnect. The exception is thrown in `Utils.messageToBuffer` method, and the following code will not execute

**Comment by MirrorZyb** [comment]
> You meant Google Play? Trust iOS has removed DApp browser
> 
> take a look at `personal_sign`, it handles two cases (hex / non hex)
> 
> ```js
>   personal_sign(payload) {
>     const message = payload.params[0];
>     const buffer = Utils.messageToBuffer(message);
>     if (buffer.length === 0) {
>       // hex it
>       const hex = Utils.bufferToHex(message);
>       this.postMessage("signPersonalMessage", payload.id, { data: hex });
>     } else {
>       this.postMessage("signPersonalMessage", payload.id, { data: message });
>     }
>   }
> ```


I accessed it through WalletConnect. The exception is thrown in Utils.messageToBuffer method, and the following code will not execute

**Comment by hewigovens** [comment]
hmm, I'm confused, what does WalletConnect do with `Utils.messageToBuffer`? It's web3 provider in dapp browser, could you please elaborate your question again? what's the steps to reproduce, what's your app / os version?

**Comment by hewigovens** [comment]
We tried Trust Android, it seems not working, will try to fix it soon

**Comment by MirrorZyb** [comment]
> We tried Trust Android, it seems not working, will try to fix it soon

Thanks you

> We tried Trust Android, it seems not working, will try to fix it soon

Thanks you
