### ISSUE TITLE
The method is invalid. Can you help solve it (kotlin)

### ISSUE THREAD

**Issue by hongyantao** [trustwallet/trust-web3-provider#168]
requestAccounts and  signTransaction  sendError The method is invalid
context.post {
                            val text = "Canceled"
                            val callback = "window.ethereum.sendError($id,\"$text\")"
                            context.evaluateJavascript(callback) { value ->
                                println(value)
                            }
                        }
signTypedMessage  How about kotlin signature method? Thank you

**Comment by hewigovens** [comment]
please refer to iOS example, the flow is very similar
