### ISSUE TITLE
connect trust wallet and show user his btc address

### ISSUE THREAD

**Issue by optima66** [trustwallet/trust-web3-provider#169]
https://developer.trustwallet.com/wallet-connect/dapp

 i am trying to connect my app and show user all his supported addresses
I do it like this:

import WalletConnect from "@walletconnect/client";
import QRCodeModal from "@walletconnect/qrcode-modal";

const connector = new WalletConnect({
  bridge: "https://bridge.walletconnect.org", // Required
  qrcodeModal: QRCodeModal,
});
connector.on("connect", (error, payload) => {
  // Get provided accounts and chainId
  const { accounts, chainId } = payload.params[0];
  console.log(accounts)

But i got only 15 blockchains:
see this screenshot:
https://i.imgur.com/h1X1Yix.jpg 

I ave 2 questions:

1. how do i get other coin addresses ,btc for example? (there is no btc on the screen)

2. where is the list of all this network ids?

**Comment by hewigovens** [comment]
1. currently we only support coins in wallet core that implements json protobuf signing, bitcoin is not supported
2. https://github.com/trustwallet/wallet-core/blob/master/registry.json
