### ISSUE TITLE
web3 variations and support

### ISSUE THREAD

**Issue by mandelmonkey** [TrustWallet/trust-web3-provider#17]
Appolgies not really an issue but an inquiry
I developed a dapp browser using the metamask provider repo https://github.com/MetaMask/provider-engine

However when loading some notable dapps (that work with the metamask chrome extension) in my dapp browser I get the error Web3ProviderEngine does not support synchronous requests

I see the dapp is calling synchronous methods (web.eth.accounts[0]) but seems like they should be calling async however the dapps works in the metamask chrome extension. I switched to using teh trust provider instead and the dapps also now work

So my question is what is the standard here? seems dapps should be using the async method but most arent, is there any official guideline on this? or a good place to find out more?

thanks!

**Comment by mandelmonkey** [comment]
Thanks for the reply
so that means current dapps will have to upgrade or they will stop working?
the reason I ask is a game didnt work in our dapp browser but worked in trust wallet (due to synchronous request), so I changed our provider to use this one and it works, however it means their dapp will some working after the upgrade to 1.0.0?

**Comment by mishfit** [comment]
That's correct, for the most part, the game will stop working after the upgrade to 1.0.0.

It is possible for them to bring along they're own version of web3 and just use trust wrapped in web3. You'll see this in MetaMask's own [documentation](https://github.com/MetaMask/faq/blob/master/DEVELOPERS.md) but most people ignore the second part of the code:

```js
if (typeof web3 !== 'undefined') {
    // use built-in provider
    web3js = new Web3(web3.currentProvider);
  } else {
    // ***fallback*** - use your fallback strategy (local node / hosted node + in-dapp id mgmt / fail)
    web3js = new Web3(new Web3.providers.HttpProvider("http://localhost:8545"));
  }
```
The brilliant part is that you can take `web3.currentProvider` and wrap it in [EthJS](https://github.com/ethjs/ethjs) or something else using web3 0.20.x syntax.

There's lots of options they just need to pick one

**Comment by mandelmonkey** [comment]
thanks so, let me see if I undertand this
 the trust js injected code that interacts with the wallet i.e.
```
 const addressHex = "\(address)"
        const rpcUrl = "\(sessionConfig.server.rpcURL.absoluteString)"
        const wssUrl = "\(sessionConfig.server.wssURL.absoluteString)"
        const chainID = "\(sessionConfig.chainID)"

        function executeCallback (id, error, value) {
          trust.executeCallback(id, error, value)
        }

        const trust = new Trust({
          rpcUrl,
          wssUrl,
          getAccounts: function (cb) { cb(null, [addressHex]) },
          processTransaction: function (tx, cb){
            console.log('signing a transaction', tx)
            const { id = 8888 } = tx
            trust.addCallback(id, cb)
            webkit.messageHandlers.signTransaction.postMessage({"name": "signTransaction", "object": tx, id: id})
          },
          signMessage: function (msgParams, cb) {
            const { data } = msgParams
            const { id = 8888 } = msgParams
            console.log("signing a message", msgParams)
            trust.addCallback(id, cb)
            webkit.messageHandlers.signMessage.postMessage({"name": "signMessage", "object": { data }, id: id})
        },
          signPersonalMessage: function (msgParams, cb) {
            const { data } = msgParams
            const { id = 8888 } = msgParams
            console.log("signing a personal message", msgParams)
            trust.addCallback(id, cb)
            webkit.messageHandlers.signPersonalMessage.postMessage({"name": "signPersonalMessage", "object": { data }, id: id})
          },
```

will still continue to work if the dapp uses their own web3 provider?
do you know when the upgrade is scheduled?

**Comment by vikmeup** [comment]
This should be fixed now
