### ISSUE TITLE
How to use the   "signTransaction" ？It's not in the demo， Can you add an example？

### ISSUE THREAD

**Issue by liuzhenLz** [trustwallet/trust-web3-provider#171]
How to use the   "signTransaction" ？It's not in the demo， Can you add an example？

**Comment by liuzhenLz** [comment]
I can get a response from the Dapp,But the Dapp doesn't know if my deal has been signed： 
 var script = $"window.ethereum.sendResponse({id}, \"{signedResult}\")";

**Comment by hongyantao** [comment]
both iOS and Android?

**Comment by liuzhenLz** [comment]
The iOS platform

**Comment by hewigovens** [comment]
the flow should be same as signing a message, if you can sign a message, you can sign a tx

**Comment by hongyantao** [comment]
@hewigovens I can authorize and pay here, cancel payment without callback, repurchase without callback, return null, what should I do?

**Comment by WhiteCjy** [comment]
@hewigovens Can you use this to load the third-party DAPP successfully? I use it to try to connect to the one that is not connected to uniswap

**Comment by liuzhenLz** [comment]
> @hewigovens I can authorize and pay here, cancel payment without callback, repurchase without callback, return null, what should I do?
I had the same problem

**Comment by DSBUGAY2** [comment]
R

**Comment by DSBUGAY2** [comment]
one1yr7j2xulp5z2z54sshvzzx0yque4wwsd6xw6zq

**Comment by hewigovens** [comment]
@liuzhenLz Steps to handle `signTransaction`:
1. Extract tx data from `object` field, you may see something similar to 
```json
{
        "data": "0xd46e8dd67c5d32be8d46e8dd67c5d32be8058bb8eb970870f072445675058bb8eb970870f072445675",
        "from": "0xb60e8dd61c5d32be8058bb8eb970870f07233155",
        "gas": "0x76c0",
        "gasPrice": "0x9184e72a000",
        "to": "0xd46e8dd67c5d32be8058bb8eb970870f07244567",
        "value": "0x9184e72a"
}
```
2. Use wallet core or other libraries to sign this tx (https://github.com/trustwallet/wallet-core/blob/master/swift/Tests/Blockchains/EthereumTests.swift#L24)
3. Broadcast the signed tx and call `window.ethereum.sendResponse` with `payload.id` and tx id
