### ISSUE TITLE
部分方法调取回调为null,作者能给个建议吗?

### ISSUE THREAD

**Issue by hongyantao** [trustwallet/trust-web3-provider#173]
互联网能找到的大部分是这些DApp的玩法,没有对接,交互,报错处理的办法,作者可以告诉我们,这些方法是根据什么定义的,android和ios是不是有不一样的地方,如果能有ios的对接文档就更好,作者能给我解答不,我是真的没办法了

**Comment by hongyantao** [comment]
或者告诉我朝那个方向找答案也可以

**Comment by hewigovens** [comment]
iOS 的 demo 已经比较完善了，你问的问题实在很难回答：
1. 没有上下文
2. 没有详细的报错，或者sample code
3. 期望的结果是什么

**Comment by hongyantao** [comment]
@hewigovens  

1. 调 **signTransaction** 方法弹窗点击左上角关闭  **Canceled** 方法  ios 的会在面板给一个**未知错误:"用户取消操作"** , android 这边回调为**System.out: null** ,卡在 **等待确认** ,android这边需要和ios一样的回调
**ios code**
 alert.addAction(UIAlertAction(title: "Cancel", style: .destructive, handler: { [weak webview] _ in
            webview?.sendError("Canceled", to: id)
        }))

**android code**
    context.post {
            val error = "Canceled"
            val callback = "window.ethereum.sendError(${obj["id"] as Long},\"$error\")"
            context.evaluateJavascript(callback) { value ->
                println(value)
            }
        }
2. 调 **signTypedMessage**方法,使用代币DAI回购ETH,android 卡 允许 UniSwap 调用你的DAI 无法授权 
    **ios code**
 alert.addAction(UIAlertAction(title: "OK", style: .default, handler: { [weak webview] _ in
            let signed = self.signMessage(data: data, addPrefix: false)
            webview?.sendResult("0x" + signed.hexString, to: id)
        }))

**ios加签方法**
 private func signMessage(data: Data, addPrefix: Bool = true) -> Data {
        let message = addPrefix ? Hash.keccak256(data: ethereumMessage(for: data)) : data
        var signed = privateKey.sign(digest: message, curve: .secp256k1)!
        signed[64] += 27
        return signed
    }
    **android code**
         context.post {
                        val result = signMessageETH(data as String)
                        val callback = "window.ethereum.sendResponse(${obj["id"] as Long},\"${result}\")"
                        context.evaluateJavascript(callback) { value ->
                            println(value)
                        }
                    }
**android加签方法**
    android 加签后,默认在字符串前面加了0x , 这个不知道什么原因
    private fun signMessageETH(data: String): String {
        val prKey = PrivateKey(getWallet()?.privateKey?.toHexByteArray())
        val signed = prKey.sign(data.toHexByteArray(), Curve.SECP256K1)
        signed[64] = (signed[64] + 27).toByte()
        return signed.toHexString()
    }
3.所有的 取消方法 回调都是 null 
    context.post {
            val error = "Canceled"
            val callback = "window.ethereum.sendError(${obj["id"] as Long},\"$error\")"
            context.evaluateJavascript(callback) { value ->
                println(value)
            }
        }
4.期望流程能和ios一样,能取消有回调,代币回购能授权成功 ,先谢谢作者帮忙解答

**Comment by hongyantao** [comment]
android 卡在   **等待确认**  这里
![lADPDh0cQM1P4rDNCQfNBDg_1080_2311 jpg_720x720q90g](https://user-images.githubusercontent.com/38758237/129650784-3a8a5f09-8367-436a-ab5c-edf1508bd45f.jpg)
**ios 取消提示**
![lALPDh0cQM1P4qzNCF7NBNo_1242_2142](https://user-images.githubusercontent.com/38758237/129650683-3b56d1bb-3cfb-42e8-bf84-13fceddb63e3.png)

**Comment by hongyantao** [comment]
**android回购ETH无法授权的DAI**
![c2d4ab0b74ae6afec0f37fe4ac75916](https://user-images.githubusercontent.com/38758237/129650935-e5ce8a76-a238-4fba-b95a-142ef8e6b6f7.jpg)

**Comment by hewigovens** [comment]
iOS 和 Android webview 的 `evaluateJavascript` callback 本来就不会有返回值的 (`sendError` 和 `sendResponse` 都没有返回值)，你的问题看上去是 webview 处理的问题？比如 js 有错误，或者调用 `sendError` 或者 `sendResponse` 的 id 不对？

**Comment by liuzhenLz** [comment]
交易完一直在Padding 中 和授权失败时怎么会儿呢大佬

**Comment by liuzhenLz** [comment]
> 互联网能找到的大部分是这些DApp的玩法,没有对接,交互,报错处理的办法,作者可以告诉我们,这些方法是根据什么定义的,android和ios是不是有不一样的地方,如果能有ios的对接文档就更好,作者能给我解答不,我是真的没办法了

授权失败和交易完上链后Dapp那边一直显示Padding获取不到交易记录是怎么事儿呢，有遇到吗。

**Comment by hongyantao** [comment]
@liuzhenLz  那个页面呀? 是ios吗

**Comment by WhiteCjy** [comment]
老哥，你用这个库能连上uniswap？我拿demo跑连不上,能给个参考吗

**Comment by hongyantao** [comment]
@WhiteCjy 
你把android的Demo里面两个类复制下来,路径改完  
>  https://app.uniswap.org/#/swap  
然后给你的钱包授权.功能未完成 ,只能用ETH对换其他币种,无法回购,这个不知道怎么解决

**Comment by CubeFeng** [comment]
@hongyantao 
我现在遇到的问题：在 demo 里直接将 url 改为 “https://app.uniswap.org/#/swap”，运行 app 时没有任何反应，不会收到任何回调。“https://js-eth-sign.surge.sh” 页面是点击 connect 按钮后触发了 eth_requestAccounts 授权连接，我想要那种加载 Uniswap 链接后直接弹授权框（不需要手动点击连接）需要如何实现呢？

**Comment by hongyantao** [comment]
@CubeFeng 
android demo 有合并的新代码
1. loadInitJs(1, "https://api.mycryptoapi.com/eth");  参数1.默认为 1 (ETH) , 参数2.uniswap 主币为ETH
2. webview.loadUrl("https://uniswap.token.im")
