### ISSUE TITLE
iOS： after click connect，log my address ,but web page not show myAddress.

### ISSUE THREAD

**Issue by wkn66** [trustwallet/trust-web3-provider#180]
requestAccounts走完以后 ，log出我的地址了，但是依然显示连接钱包，那儿没有显示出我的地址,我用的https://app.uniswap.org/

**Comment by wkn66** [comment]
> requestAccounts走完以后 ，log出我的地址了，但是依然显示连接钱包，那儿没有显示出我的地址,我用的https://app.uniswap.org/

reasion:rpc doesn't correspond to chainID

**Comment by z1joey** [comment]
I got the same issue, did you solve it?
