### ISSUE TITLE
Can you provide a API doc or method list?

### ISSUE THREAD

**Issue by sskeater** [TrustWallet/trust-web3-provider#2]
Hi, I want to use trust.js to implements my wallet. Can you provide a API doc or method list to help us learn about trust.js?

**Comment by vikmeup** [comment]
Please refer to https://github.com/TrustWallet/trust-wallet-ios! It's been implemented on the Trust wallet.

**Comment by mishfit** [comment]
@sskeater you're really going to want to look at the provider engine from MetaMask: https://github.com/MetaMask/provider-engine/

This provider just creates a very specific instance of a provider engine with everything that the Trust wallet needs
