### ISSUE TITLE
sendResponse and sendError are failed

### ISSUE THREAD

**Issue by Shawn0920** [trustwallet/trust-web3-provider#203]
I encountered a problem in android device when I have to call sendResponse to pass the tx hash or call sendError to pass the error message, after the DApp is signed on the chain.

I check the js method, it need to find the callback by id, But this step will report an error, callback is undefined.
![image](https://user-images.githubusercontent.com/17979403/142717155-74a507df-d426-43ca-aec3-36ad93445925.png)

sendResponse function is same problem.Similarly, it will execute the method in else
![image](https://user-images.githubusercontent.com/17979403/142717271-e028507e-db17-4dd6-963e-96846d817ba5.png)

So, what is the cause of the above problem? And what should I do?

**Comment by FirstVoyager** [comment]
How do you add to webview and load (example: uni swap) on it?

**Comment by Shawn0920** [comment]
Thank you for help me.

![image](https://user-images.githubusercontent.com/17979403/147334516-2fa4ac96-4c39-45ec-aebf-d5f6b8b34d60.png)
![image](https://user-images.githubusercontent.com/17979403/147334572-2b1c956d-37c9-4d3c-98e5-77c054a31e5d.png)
![image](https://user-images.githubusercontent.com/17979403/147334639-e020d252-eba9-42db-a543-b39b8b4aca95.png)
![image](https://user-images.githubusercontent.com/17979403/147335074-0971f250-6e6e-4963-9437-e5b36b521dd6.png)


I try to link pancakswap, that is ok.
But the sushi is failed when I try to link.
So I don’t know where the problem is

**Comment by WhiteCjy** [comment]
Have you solved this problem?can you help me
