### ISSUE TITLE
trustwallet-core for native Kotlin/Swift-UI

### ISSUE THREAD

**Issue by cryptodev100** [trustwallet/trust-web3-provider#205]
https://github.com/trustwallet/wallet-core is a great library and I like the clean structure of its C++-code.
However, I am still struggling to implement full network-functionality for https://github.com/trustwallet/wallet-core.

So I discovered this repo which implements a web3-provider on top of trustwallet-core.
Based on the demo-apps in this repo, the purpose of this repo seems to connect a WebView to trustwallet-core for Android/iOS?

Unfortunately, I cannot use most of the demo-code because I have to use native Kotlin/Swift-code (without using a WebView for the UI).
Now my question is if there exists a similar demo-app that uses native code instead of a WebView.
Is there a library that implements similar functionality with Kotlin and Swift instead of JavaScript?

**Comment by hewigovens** [comment]
this repo is specifically for ethereum web3 dapp, not native code; you could try https://github.com/argentlabs/web3.swift or similar libraries
