### ISSUE TITLE
Some dapp chains in bsc are not recognized correctly

### ISSUE THREAD

**Issue by windswrold** [trustwallet/trust-web3-provider#220]
hello, I have a problem can you help me？

dapp url : https://unicorn.metaspaceunicorn.com/#/invitation
chainId: 56
rpcUrl: https://bsc-dataseed2.binance.org
address:0x4e268c89495254288b4D1Cb4bc4c010f8C009b25

When opening this dapp url , clicking "connect wallet" will prompt "please switch to the ''bsc" network" . But the data I sent is bsc network, what is the reason?
There are several dapps, all of which will prompt the wrong network.

**Comment by hewigovens** [comment]
Can you contact the dapp developer how they detect and connect web3? It doesn't use modern `requestsAccount` rpc method, also do you have other dapp example?

**Comment by windswrold** [comment]
I can't contact the developer of the dapp, all I know is that there are these issues, these projects are in the 'bsc' network。
And these:
https://bitbyte.finance/   
https://nft.metabasis.site

**Comment by hewigovens** [comment]
I can confirm that those apps use legacy Metamask `networkVersion` property https://docs.metamask.io/guide/ethereum-provider.html#legacy-properties, the best way is to ask them using `eth_chainId` rpc, the workaround is to set `networkVersion`

**Comment by windswrold** [comment]
thanks.
I set selectedAddress, networkVersion, chainId, and that's true.
And how did you find out, I have been looking for a long time and have no clue

**Comment by hewigovens** [comment]
Should be fixed in this pr: https://github.com/trustwallet/trust-web3-provider/pull/221
