### ISSUE TITLE
WalletConnect Issues

### ISSUE THREAD

**Issue by jojoclt** [trustwallet/trust-web3-provider#224]
Cannot sign transaction using TrustWallet on android, but can on ios.
When sign transaction on opensea it shows java.lang.IllegalStateException

**Comment by hewigovens** [comment]
Can you record a video to reproduce this issue? What's the app version and android os version?

**Comment by jojoclt** [comment]
Android 12
App 5.9
https://we.tl/t-pqqrg4Tq4J

**Comment by vcoolish** [comment]
What kind of transaction is that? Do you have request? What is the dapp?

**Comment by jojoclt** [comment]
> What kind of transaction is that? Do you have request? What is the dapp?

The dapp is OpenSea connecting via Wallet Connect, (using qrcode to scan)
To reproduce the issue,
Listing nfts on opensea, or lowering the price of already listed nft.

I don't have the request because I use the qrcode to scan walletconnect on my pc

**Comment by jojoclt** [comment]
How can I help you reproduce the bug? Because it just shows the error

**Comment by vcoolish** [comment]
Some of eth_sign_type_data requests from opensea come in incorrect format, we will handle it in next release, thanks

**Comment by jojoclt** [comment]
It is fixed, thanks
