### ISSUE TITLE
Could you guys allow to import Ontology private key?  (like for Solana)

### ISSUE THREAD

**Issue by Princeobinna** [trustwallet/trust-web3-provider#231]
Could you guys allow to import Ontology private key?  (like for Solana)

__Originally posted by @roccomuso in https://github.com/trustwallet/assets/issues/18616__

**Comment by hewigovens** [comment]
Solana needs it for some coin migration (KIN), why do we need it for Ontology"?

**Comment by roccomuso** [comment]
compatibility with other wallets.

**Comment by Princeobinna** [comment]
How??

**Comment by Princeobinna** [comment]
Ok, thanks.
