### ISSUE TITLE
Walletconnect V2 support

### ISSUE THREAD

**Issue by dokocat** [trustwallet/trust-web3-provider#232]
It would be great to get Walletconnect V2 supported as it includes new features and stability improvements.

**Comment by hewigovens** [comment]
Will support it soon

**Comment by dokocat** [comment]
Is there an issue that tracks the progress of v2 support?

**Comment by WyattMufson** [comment]
@hewigovens any update on this?

**Comment by hewigovens** [comment]
Should be alive in app store
