### ISSUE TITLE
EIP-712 Signing is not coming to the mobile device

### ISSUE THREAD

**Issue by addmorebass** [trustwallet/trust-web3-provider#247]
Our users are trying to sign an EIP-712 payload, and it is not popping up on the screen. I used Rainbow via WalletConnect and it did work, so I have isolated the issue to Trust Wallet.

**Comment by hewigovens** [comment]
Is it Trust iOS or Android? How to reproduce it with your dapp?

**Comment by addmorebass** [comment]
Hey, this is on iOS with Tokemak.xyz. You would have to stake $TOKE and vote to access the signing. We can discuss offline if you need some to reproduce.

**Comment by hewigovens** [comment]
Yeah, could you reach me on telegram? @hewig

**Comment by hewigovens** [comment]
This should be fixed in a new version

**Comment by addmorebass** [comment]
Thanks for your help @hewigovens! Please can you comment here once it is released? I can retest one my side.

**Comment by ArtemGoryunov** [comment]
@addmorebass new version (7.2) with the fix was released
