### ISSUE TITLE
Have such a problem - Attempted import error: './id_mapping' does not contain a default export (imported as 'IdMapping').

### ISSUE THREAD

**Issue by SweetPad** [trustwallet/trust-web3-provider#248]
when we want to use this - got this kind of problem 

Attempted import error: './id_mapping' does not contain a default export (imported as 'IdMapping').

**Comment by hewigovens** [comment]
It's used kinda internally and not exported

**Comment by SweetPad** [comment]
Want to integrate this and give an error with the code, do you have existed place/demo that I can check and see whether works or not this package?

**Comment by hewigovens** [comment]
Do you want to access it from provider or just use it separately? The code is dead simple tho: https://github.com/trustwallet/trust-web3-provider/blob/master/src/id_mapping.js
