### ISSUE TITLE
Can't get user address

### ISSUE THREAD

**Issue by mnatsakanyan** [trustwallet/trust-web3-provider#251]
I call like this 

a = new TrustWeb3Provider();
a.eth_Accounts();

It returs null; how can use this ?

for the connection I just call the class then try to get eth_Accounts();

Please tell me the process to get account.

**Comment by SweetPad** [comment]
Do you have any demo that I can check how call it and how get address, I checked your tests and saw when you call the provider you give also address for checking, but where did you take the address? - I need to have at first that address - where can I get it ?

**Comment by mnatsakanyan** [comment]
Do you have any demo that I can check how call it and how get address, I checked your tests and saw when you call the provider you give also address for checking, but where did you take the address? - I need to have at first that address - where can I get it ?

**Comment by mnatsakanyan** [comment]
Code doesn't work - if you can advice something then will be better

**Comment by Supportprotocol** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14232768/

**Comment by SUPPORTTEAMHERR** [comment]
> Code doesn't work - if you can advice something then will be better

We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by SUPPORTTEAMHERR** [comment]
> 
> Do you have any demo that I can check how call it and how get address, I checked your tests and saw when you call the provider you give also address for checking, but where did you take the address? - I need to have at first that address - where can I get it ?
> 
> 

We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by SUPPORTTEAMHERR** [comment]
> I call like this 
> 
> a = new TrustWeb3Provider();
> a.eth_Accounts();
> 
> It returs null; how can use this ?
> 
> for the connection I just call the class then try to get eth_Accounts();
> 
> Please tell me the process to get account.
> 

We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by CustomerTeam001** [comment]
@mnatsakanyan We'd be happy to look into this for you 
kindly file a support ticket below 
https://forms.gle/FhSmn4AznQtZcruX8
