### ISSUE TITLE
[INFO:CONSOLE(831)] "callback id: 1650171612712 not found", source:  (831)

### ISSUE THREAD

**Issue by WhiteCjy** [trustwallet/trust-web3-provider#254]
val script = "window.ethereum.sendResponse($methodId, \"$message\")"
按照收到的id，然后回调回去报这个找不到是什么原因

**Comment by WhiteCjy** [comment]
https://uniswap.token.im/
出现在uni-swap测试网上，用bsc上的dapp测试又没发现这个问题

**Comment by WhiteCjy** [comment]
用了sushi swap测试
也是同样的问题
https://app.sushi.com/swap
网络分别是https://ropsten.infura.io/v3/54828bfa2cb14873a43512fd8d3fc24b
chainId是3

**Comment by WhiteCjy** [comment]
解决了，android加载这些dapp需要在onPageStart的时候就注入js，不要在onPageFinish的时候注入。
作者可以整理下这些问题啊，demo也是在finish的时候注入，误导

**Comment by hewigovens** [comment]
@WhiteCjy could you please help update the demo? it might help others, thanks 🙏
