### ISSUE TITLE
Android TrustWallet can't detect WalletConnect session disconnect

### ISSUE THREAD

**Issue by OptimisticQuan** [trustwallet/trust-web3-provider#255]
English version is at BOTTOM

中文：
安卓版本通过"wc:"协议唤起连接的，不能准确的检测WalletConnect断开连接，并且当应用在后台被杀掉时，调用签名唤起时会导致InvalidSession

用例1： 当使用TrustWallet扫码电脑浏览器网页WalletConnect二维码连接后。点击网页断开连接，TrustWallet可以正常检测断开，退出WalletConnect。
用例2： 当使用TrustWallet扫码电脑浏览器网页WalletConnect二维码连接后。在TrustWallet退出并断开Session，网页正常断开连接。
用例3： 当在手机浏览器点击连接WalletConnect，并唤起TrustWallet连接后。切换回手机浏览器，点击网页断开连接，切回TrustWallet，发现并未识别出session已断开，此时再次切回手机网页连接TrustWallet将无法弹出连接确认框。
用例4： 当在手机浏览器点击连接WalletConnect，并唤起TrustWallet连接后。在TrustWallet退出并断开Session，手机浏览器网页正常断开连接。
用例5： 当在手机浏览器点击连接WalletConnect，并唤起TrustWallet连接后。后台杀掉TrustWallet，手机网页内调用签名操作，唤起TrustWallet，显示"Invalid Session"。
用例6： 当在手机浏览器点击连接WalletConnect，并唤起TrustWallet连接后。后台杀掉TrustWallet，重新运行TrustWallet。手机网页内调用签名操作，唤起TrustWallet可以正常签名。

结论：
1. 安卓版本通过"wc:"协议唤起连接的，不能很好的检测WalletConnect断开连接。
2. 当应用在后台被杀掉时，调用签名唤起时会导致InvalidSession。

English: 
The Android version, which invokes the connection via the "wc:" protocol, does not detect WalletConnect disconnections well and causes an InvalidSession when the application is killed in the background and the signature is called to invoke it.

Use Case 1: When using TrustWallet to scan the WalletConnect QR code on a computer browser webpage to connect. When clicking on the web page to disconnect, TrustWallet detects the disconnection normally and exits WalletConnect.
Use Case 2: When using TrustWallet to scan the WalletConnect QR code on a computer browser webpage to connect. After TrustWallet exits and disconnects the Session, the web page disconnects normally.
Use Case 3: When you click on Connect to WallectConnect in your mobile browser to bring up TrustWallect and successfully connect. Switching back to the mobile browser, clicking on the web page to disconnect and switching back to TrustWallet, it was found that the session was not recognised as disconnected.
Use Case 4: When you click on Connect to WallectConnect in your mobile browser to bring up TrustWallect and successfully connect. After TrustWallet exits and disconnects from the Session, the mobile browser web page disconnects normally.
Use Case 5: When you click on Connect to WallectConnect in your mobile browser to bring up TrustWallect and successfully connect. The background kills the TrustWallet and the mobile web page invokes the signature operation, which brings up the TrustWallet and displays "Invalid Session".
Use Case 6: When you click on Connect to WallectConnect in your mobile browser to bring up TrustWallect and successfully connect. Kill TrustWallet and reopen it, The signature operation is invoked from within the mobile web page and the TrustWallet is invoked with a normal signature.

Conclusion.
1. the Android version, which calls up the connection via the "wc:" protocol, does not detect WalletConnect disconnections well.
2. When the application is killed in the background, the signature call will result in an InvalidSession.

**Comment by hewigovens** [comment]
@vcoolish is working on multi session support, will release a new version for this
