### ISSUE TITLE
iOS signTransaction

### ISSUE THREAD

**Issue by liuxingyubm** [trustwallet/trust-web3-provider#271]
After connecting my wallet, I want to swap. After I click swap, return to me with the signTransaction method，But I find didn't implement that in the demo, So I called the handleSignMessage method，But the error message returned is as follows, and I don't know what's wrong with it。There are only a few methods for iOS in the main demo。
<img width="800" alt="WeChateb73921e8af966262308e11086c8f3a9" src="https://user-images.githubusercontent.com/100563041/166872805-31c65ec6-89e7-44c6-b0d9-50bb3f3d2a1d.png">

**Comment by ronaldoguedess** [comment]
me too! did u find something?

**Comment by hewigovens** [comment]
You just need to map the tx object to Trust Wallet Core Ethereum SigningInput then sign it
```json
{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "eth_signTransaction",
  "params": [
    {
      "data": "0xd46e8dd67c5d32be8d46e8dd67c5d32be8058bb8eb970870f072445675058bb8eb970870f072445675",
      "from": "0xb60e8dd61c5d32be8058bb8eb970870f07233155",
      "gas": "0x76c0",
      "gasPrice": "0x9184e72a000",
      "to": "0xd46e8dd67c5d32be8058bb8eb970870f07244567",
      "value": "0x9184e72a"
    }
  ]
}

```
Sample request from: https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_signtransaction. 
Trust Wallet Core swift test case: https://github.com/trustwallet/wallet-core/blob/master/swift/Tests/Blockchains/EthereumTests.swift#L25

**Comment by ronaldoguedess** [comment]
How can I map that?

Do I need to sign just the params object?

<pre>
```
{
      "data": "0xd46e8dd67c5d32be8d46e8dd67c5d32be8058bb8eb970870f072445675058bb8eb970870f072445675",
      "from": "0xb60e8dd61c5d32be8058bb8eb970870f07233155",
      "gas": "0x76c0",
      "gasPrice": "0x9184e72a000",
      "to": "0xd46e8dd67c5d32be8058bb8eb970870f07244567",
      "value": "0x9184e72a"
    }
```
</pre>

what about the "data"?

**Comment by hewigovens** [comment]
@ronaldoguedess you can use `ContractGeneric` 

```swift
$0.transaction = EthereumTransaction.with {
                $0.contract_generic = EthereumTransaction.ContractGeneric.with {
                    $0.amount = Data(hexString: "0x9184e72a")!
                    $0.data = Data(hexString: "0xd46e8dd67c5d32be8d46e8dd67c5d32be8058bb8eb970870f072445675058bb8eb970870f072445675")!
                }
            }
```

**Comment by ronaldoguedess** [comment]
> @ronaldoguedess you can use `ContractGeneric`
> 
> ```swift
> $0.transaction = EthereumTransaction.with {
>                 $0.contract_generic = EthereumTransaction.ContractGeneric.with {
>                     $0.amount = Data(hexString: "0x9184e72a")!
>                     $0.data = Data(hexString: "0xd46e8dd67c5d32be8d46e8dd67c5d32be8058bb8eb970870f072445675058bb8eb970870f072445675")!
>                 }
>             }
> ```

_**contract_generic**_ won't exist on Kotlin or Java. I'm Android developer. and I'm facing the same problem of these two guys because this function won't be implemented on the demo.

If you know about android, check that, please.
https://github.com/trustwallet/trust-web3-provider/issues/304

**Comment by zzzkk** [comment]
I'm not sure if it is the same case but I think it is a great chance

I noticed that `eth_sendTransaction` is mapped to `signTransaction` event in [trust-min.js script](https://github.com/trustwallet/trust-web3-provider/blob/master/dist/trust-min.js) which can be really confusing because it suggests that it is `eth_sindTransaction` not send
> function eth_sendTransaction(payload){this.postMessage("signTransaction",payload.id,payload.params[0])}}

so the resolution is just to send it and pass tx hash not the signature 😅  or fix the script ofc
