### ISSUE TITLE
Проблема после подтверждения транзакции

### ISSUE THREAD

**Issue by MUSystem** [TrustWallet/trust-web3-provider#28]
В коде Dapp вызываю по кнопке в форме функцию контракта:

`    miniToken.deposit( { from: address, value: amountinwei })
     .then(function (txHash) {
     alert('Transaction sent ' + txHash); 
      })
     .catch(console.error) `

Далее подтверждаю транзакцию во всплывающем окошке кошелька. 

Используя Метамаск, алерт срабатывает после подтверждения транзакции. Используя Траст (андроид), не срабатывает. Проблема появилась после 12 сентября (точную дату не назову, но 12го точно всё работало - есть видео). С этого момента был ряд обновлений кошелька.

Прошу проверить или подсказать вариант решения для меня. Кстати, было бы удобно использовать сеть Ropsten для отлова багов, но тестовые сети теперь недоступны.

Заранее благодарю!

**Comment by MUSystem** [comment]
Перенесу в Android app

**Comment by MUSystem** [comment]
1.6.136

**Comment by madcake** [comment]
Could you make something same https://danfinlay.github.io/js-eth-personal-sign-examples/

**Comment by MUSystem** [comment]
Не совсем понял, извините. 
Мне следует выполнить все тесты на приведенной Вами странице или же создать подобную страничку, чтобы Вы смогли проверить ошибку?

**Comment by madcake** [comment]
Макет сильно бы мне помог.

**Comment by hewigovens** [comment]
what's the status of this issue? could we use English here?

**Comment by MUSystem** [comment]
Hey. Sorry for delay.

While I was preparing a sample-page for Maksim, there were several updates to the application. In one of them the issue has been corrected, for which many thanks to you! Now the alert works, as it should.

Thanks again! I close the topic.
