### ISSUE TITLE
*Is your feature request related to a problem? Please describe.**

### ISSUE THREAD

**Issue by mosesojero** [trustwallet/trust-web3-provider#319]
*Is your feature request related to a problem? Please describe.**
- I would like to have a stacking option for ENG CRYPTO Token in a trust wallet. The ENG team has their stacking system and we want to have a stacking
option in the trust wallet. This is not a problem, it's a requirement or a suggestion.
https://bscscan.com/token/0x8a505d5cb3db9fcf404c0a72af3df8be4efb707c

**Describe the solution you'd like**
ENG CRYPTO has their stacking plan like other coins and we want to implement it with trust wallet, So all stacking will be done by trust wallet and
there can be a stacking fee for every users that will go to Trust wallet.

**Describe alternatives you've considered**
Alternatives They are doing their own standalone system already but it would be much better with trust wallet and then We can provide web services for other
token to start their stacking system on trust wallet for BEP20 Tokens

**Additional context**
Please try to get my point and if it required any more explanations i can answer or explain any questions related to this Stacking option

Thank you 

__Originally posted by @yenky in https://github.com/trustwallet/assets/issues/22144__

**Comment by yenky** [comment]
Hi ,
I want to reopen this. I 'm really sorry for not replying on time.

thank you
