### ISSUE TITLE
How to notify DAPP that "chainId" has changed after "switchEthereumChain" method is called?

### ISSUE THREAD

**Issue by ronaldoguedess** [trustwallet/trust-web3-provider#321]
I implemented the new method "switchEthereumChain", which is called when I click to switch chain in DAPP "sushi.swap",
but I am not able to notify the Dapp that the Chain was changed. (Note: Without refresh the page)

With the code below, I managed to show the ETH token, instead BNB, but it didn't load their balance. what would be the correct way to notify the DAPP chain change and update the DApp?

<pre>webview.evaluateJavascript("window.ethereum.emitConnect(1)", null)

**Comment by hewigovens** [comment]
try `window.ethereum.emitChainChanged` method, the value is hex string chain id

**Comment by badjone** [comment]
initjs how to refresh the page webView
` webView.post {
      webView.evaluateJavascript(initJs, null)
   }
   webView.emitChainChanged(initJs)
   webView.sendResultNull(id)`
