### ISSUE TITLE
Support Aptos Web3 provider 

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/trust-web3-provider#328]
- https://github.com/martian-dao/aptos-web3.js
- https://github.com/aptos-labs/petra-wallet-types/blob/main/index.d.ts

<img width="627" alt="image" src="https://user-images.githubusercontent.com/360470/191674568-f644a157-4bb5-4517-afad-e70f4e9cf9f6.png">

**Comment by Nanimustshine** [comment]
> - https://github.com/martian-dao/aptos-web3.js
> - https://github.com/aptos-labs/petra-wallet-types/blob/main/index.d.ts
> 
> <img width="627" alt="image" src="https://user-images.githubusercontent.com/360470/191674568-f644a157-4bb5-4517-afad-e70f4e9cf9f6.png">
> 

Kindly file a support ticket for this concern below
https://forms.gle/KAqYDCGHb1UP4K8e7
