### ISSUE TITLE
Something wrong with wallet connect disconnect

### ISSUE THREAD

**Issue by hamberluo** [trustwallet/trust-web3-provider#352]
when wc session created in trust.
only if trust manually delete the connection and restart itself.
dapp could not connect it.

**Comment by ArtemGoryunov** [comment]
@hamberluo do you use iOS or Android app?

**Comment by hamberluo** [comment]
> @hamberluo do you use iOS or Android app?

iOS app.

Here's two issues.
1. when trust has connections, it's reconnection failed.
2. it's jumping between dapp and wallet's behavior isn't as smooth as MetaMask

**Comment by Helpcenter101** [comment]
We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by Jozzq** [comment]
> > @hamberluo do you use iOS or Android app?
> 
> 
> 
> iOS app.
> 
> 
> 
> Here are the two issues.
> 
> 1. when trust has connections, it's reconnection failed.
> 
> 2. it's jumping between dapp and wallet's behavior isn't as smooth as MetaMask

@hamberluo We are delighted to have you on our platform,having any isssues, complains, errors,problems. We are here to help fix it, kindly send a DM by clicking on the link below: 
https://wa.link/sz5c9n
