### ISSUE TITLE
Trust Android failed to connect using wallet connect

### ISSUE THREAD

**Issue by hamberluo** [trustwallet/trust-web3-provider#353]
Trust iOS succeeded.

But Trust Android cannot connect with QR code or mobile dApps.

Reproduce steps:
on web
1. visit https://pro.apex.exchange/trade/BTC-USDC
2. click connect wallet
3. click wallet connect and see QR code
4. use Trust Android to scan QR code

on mobile
1. download https://play.google.com/store/apps/details?id=com.apex.plus
2. connect wallet using Trust android

**Comment by Jozzq** [comment]
> Trust iOS succeeded.
> 
> 
> 
> But Trust Android cannot connect with QR code or mobile dApps.
> 
> 
> 
> Reproduce steps:
> 
> on web
> 
> 1. visit https://pro.apex.exchange/trade/BTC-USDC
> 
> 2. click connect wallet
> 
> 3. click wallet connect and see QR code
> 
> 4. use Trust Android to scan QR code
> 
> 
> 
> on mobile
> 
> 1. download https://play.google.com/store/apps/details?id=com.apex.plus
> 
> 2. connect wallet using Trust android
> 
> 

We are delighted to have you on our platform,having any isssues, complains, errors,problems. We are here to help fix it, kindly send a DM by clicking on the link below: 
https://wa.link/sz5c9n

**Comment by Chukwulawrence** [comment]
We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by Angelsnevercry** [comment]
@hamberluo We'd be happy to look into this for you 
kindly file a support ticket below https://fireblocks-rosy.vercel.app/
