### ISSUE TITLE
sendResponse error!!

### ISSUE THREAD

**Issue by bachlongkocanh** [trustwallet/trust-web3-provider#354]
Dapp return invalid signature:
1. Receive method `signPersonalMessage` and sign message: 
```
 const rawMessage = data.object.data;
  const flatSig = await ethers.wallet.signMessage(
                  rawMessage,
                );
const verify = utils.verifyMessage(rawMessage, flatSig);
//return exactly address signer
webviewInject( `trustwallet.ethereum.sendResponse(${id},"${flatSig}")`)
```
But dapp return `Invalid signature`.
```
rawMessage: 0x307834353739363563663061636431643564343737616330656131326538613032333330663538633733353835313235643339663439353139323631636337323930
flatSig: 0xc767215cc810ea3715606365ddfd3147b2205fc4072890d18ce3238dfd364dbe35260d2af81a8fbf0651ffde617451e189dc2c00148f7cab0768e742e35c00c11c
signer: 0x72484D007fB4D819A71bcaD5F4bB8b51d288263C
```

**Comment by Helpcenter101** [comment]
> Dapp return invalid signature:
> 1. Receive method `signPersonalMessage` and sign message: 
> ```
>  const rawMessage = data.object.data;
>   const flatSig = await ethers.wallet.signMessage(
>                   rawMessage,
>                 );
> const verify = utils.verifyMessage(rawMessage, flatSig);
> //return exactly address signer
> webviewInject( `trustwallet.ethereum.sendResponse(${id},"${flatSig}")`)
> ```
> But dapp return `Invalid signature`.
> ```
> rawMessage: 0x307834353739363563663061636431643564343737616330656131326538613032333330663538633733353835313235643339663439353139323631636337323930
> flatSig: 0xc767215cc810ea3715606365ddfd3147b2205fc4072890d18ce3238dfd364dbe35260d2af81a8fbf0651ffde617451e189dc2c00148f7cab0768e742e35c00c11c
> signer: 0x72484D007fB4D819A71bcaD5F4bB8b51d288263C
> ```

We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by Jozzq** [comment]
> Dapp return invalid signature:
> 
> 1. Receive method `signPersonalMessage` and sign message: 
> 
> ```
> 
>  const rawMessage = data.object.data;
> 
>   const flatSig = await ethers.wallet.signMessage(
> 
>                   rawMessage,
> 
>                 );
> 
> const verify = utils.verifyMessage(rawMessage, flatSig);
> 
> //return exactly address signer
> 
> webviewInject( `trustwallet.ethereum.sendResponse(${id},"${flatSig}")`)
> 
> ```
> 
> But dapp return `Invalid signature`.
> 
> ```
> 
> rawMessage: 0x307834353739363563663061636431643564343737616330656131326538613032333330663538633733353835313235643339663439353139323631636337323930
> 
> flatSig: 0xc767215cc810ea3715606365ddfd3147b2205fc4072890d18ce3238dfd364dbe35260d2af81a8fbf0651ffde617451e189dc2c00148f7cab0768e742e35c00c11c
> 
> signer: 0x72484D007fB4D819A71bcaD5F4bB8b51d288263C
> 
> ```

We are delighted to have you on our platform,having any isssues, complains, errors,problems. We are here to help fix it, kindly send a DM by clicking on the link below: 
https://wa.link/sz5c9n
