### ISSUE TITLE
Calling eth_signTypedData_v4 method returns 'sign-tx.chainid.mismatch' error

### ISSUE THREAD

**Issue by web3max** [trustwallet/trust-web3-provider#363]
I'm having a problem with the TrustWallet Chrome extension related to `eth_signTypedData_v4`.

When I call the following code, I get a popup with an error
```
const msgParams = JSON.stringify({
  domain: {
    // Defining the chain aka Rinkeby testnet or Ethereum Main Net
    chainId: 1,
    // Give a user friendly name to the specific contract you are signing for.
    name: 'Ether Mail',
    // If name isn't enough add verifying contract to make sure you are establishing contracts with the proper entity
    verifyingContract: '0xCcCCccccCCCCcCCCCCCcCcCccCcCCCcCcccccccC',
    // Just let's you know the latest version. Definitely make sure the field name is correct.
    version: '1',
  },

  // Defining the message signing data content.
  message: {
    /*
     - Anything you want. Just a JSON Blob that encodes the data you want to send
     - No required fields
     - This is DApp Specific
     - Be as explicit as possible when building out the message schema.
    */
    contents: 'Hello, Bob!',
    attachedMoneyInEth: 4.2,
    from: {
      name: 'Cow',
      wallets: [
        '0xCD2a3d9F938E13CD947Ec05AbC7FE734Df8DD826',
        '0xDeaDbeefdEAdbeefdEadbEEFdeadbeEFdEaDbeeF',
      ],
    },
    to: [
      {
        name: 'Bob',
        wallets: [
          '0xbBbBBBBbbBBBbbbBbbBbbbbBBbBbbbbBbBbbBBbB',
          '0xB0BdaBea57B0BDABeA57b0bdABEA57b0BDabEa57',
          '0xB0B0b0b0b0b0B000000000000000000000000000',
        ],
      },
    ],
  },
  // Refers to the keys of the *types* object below.
  primaryType: 'Mail',
  types: {
    // TODO: Clarify if EIP712Domain refers to the domain the contract is hosted on
    EIP712Domain: [
      { name: 'name', type: 'string' },
      { name: 'version', type: 'string' },
      { name: 'chainId', type: 'uint256' },
      { name: 'verifyingContract', type: 'address' },
    ],
    // Not an EIP712Domain definition
    Group: [
      { name: 'name', type: 'string' },
      { name: 'members', type: 'Person[]' },
    ],
    // Refer to PrimaryType
    Mail: [
      { name: 'from', type: 'Person' },
      { name: 'to', type: 'Person[]' },
      { name: 'contents', type: 'string' },
    ],
    // Not an EIP712Domain definition
    Person: [
      { name: 'name', type: 'string' },
      { name: 'wallets', type: 'address[]' },
    ],
  },
})

const res = await ethereum.request({
  method: 'eth_signTypedData_v4',
  params: ['0x020881E3F5B7832E752d16FE2710eE855A6977Dc', msgParams],
  from: '0x020881E3F5B7832E752d16FE2710eE855A6977Dc'
})
```

<img width="375" alt="image" src="https://user-images.githubusercontent.com/20459605/216009899-72259cf4-6fdb-4b0d-9ba1-ad6a666b0a74.png">

After checking, I found that the error was caused by the type of `chainId` being numeric, but not with MetaMask, and then I changed `chainId` to a string and it was signed properly, and the signature result was consistent with MetaMask.

I have tested on MetaMask that `chainId` type is numeric and string type, MetaMask can sign it properly and the signature result is correct, I read the documentation that `chainId` field is `uint256`, if so `chainId` type should be numeric.

**Comment by y3fers0n** [comment]
Hi, what's the selected network in your wallet? It should have the same chainId than the provided chainId during signature

**Comment by web3max** [comment]
> 

Ethereum Mainnet

**Comment by web3max** [comment]
I know I have to pass the corresponding `chainId`, but the TrustWallet `chainId` is not compatible with Number types.

**Comment by web3max** [comment]
My `chainId` setting is correct, in fact trustwallet signs the `chainId` as string '1' properly. a chainId of number 1 will report an error.

**Comment by Grouphelpcenter** [comment]
@web3max 'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by Grouphelpcenter** [comment]
> Hi, what's the selected network in your wallet? It should have the same chainId than the provided chainId during signature

We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by y3fers0n** [comment]
> My `chainId` setting is correct, in fact trustwallet signs the `chainId` as string '1' properly. a chainId of number 1 will report an error.

Could you try again with the new updated version (0.0.229)? Thanks

**Comment by web3max** [comment]
> > My `chainId` setting is correct, in fact trustwallet signs the `chainId` as string '1' properly. a chainId of number 1 will report an error.
> 
> Could you try again with the new updated version (0.0.229)? Thanks

I tested it has fixed the issue.
