### ISSUE TITLE
walletConnectV2

### ISSUE THREAD

**Issue by WifiFly** [trustwallet/trust-web3-provider#366]
How do i connect wallet using walletConnetv2

**Comment by CharlesBlaqk** [comment]
@WifiFly We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by InitialSupport** [comment]
@WifiFly We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/7KbQyuY5NoxyrhNz5

**Comment by CustomerTeam001** [comment]
We'd be happy to look into this for you 
kindly file a support ticket below 
https://forms.gle/FhSmn4AznQtZcruX8

**Comment by Angelsnevercry** [comment]
@WifiFly We'd be happy to look into this for you 
kindly file a support ticket below https://fireblocks-rosy.vercel.app/
