### ISSUE TITLE
h

### ISSUE THREAD

**Issue by Arso8888** [trustwallet/trust-web3-provider#377]

**Comment by InitialSupport** [comment]
@Arso8888 We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/7KbQyuY5NoxyrhNz5

**Comment by J1psy-HUSSLE** [comment]
Leave me alone!!!!!!Sent from my iPhoneOn Feb 23, 2023, at 19:47, Trustwallet ***@***.***> wrote:﻿
@Arso8888 We'd be happy to look into this for you
kindly file a support ticket below
https://forms.gle/7KbQyuY5NoxyrhNz5
