### ISSUE TITLE
No token files found. If you try to add/modify a token, check the name and location of your files! Logo file must be named exactly 'logo.png'. If you are not adding a token, ignore this message.

### ISSUE THREAD

**Issue by Bspring305** [trustwallet/trust-web3-provider#378]
No token files found. If you try to add/modify a token, check the name and location of your files! Logo file must be named exactly 'logo.png'. If you are not adding a token, ignore this message.

_Originally posted by @merge-fee-bot[bot] in https://github.com/trustwallet/assets/issues/23904#issuecomment-1408409091_

**Comment by CustomerTeam001** [comment]
We'd be happy to look into this for you 
kindly file a support ticket below 
https://forms.gle/FhSmn4AznQtZcruX8
