### ISSUE TITLE
### PR Summary

### ISSUE THREAD

**Issue by Tegimufranka9639** [trustwallet/trust-web3-provider#379]
### PR Summary
File `blockchains/smartchain/assets/0xeDF3ce4Dd6725650a8e9398e5C6398D061Fa7955/logo.png` is being deleted. Files should not be deleted in a PR. (Deprecated tokens should be deactivated only.)
Tokens in PR: (2)

- **ERC20** 0xcFEB09C3c5F0f78aD72166D55f9e6E9A60e96eEC
- **BEP20** 0xeDF3ce4Dd6725650a8e9398e5C6398D061Fa7955
-----
**Token BEP20 - 0xeDF3ce4Dd6725650a8e9398e5C6398D061Fa7955**:
Symbol: **VEMP** decimals: 18
Links: [Logo](https://raw.githubusercontent.com/MikeVEMP/assets/master/blockchains/smartchain/assets/0xeDF3ce4Dd6725650a8e9398e5C6398D061Fa7955/logo.png) [Info](https://raw.githubusercontent.com/MikeVEMP/assets/master/blockchains/smartchain/assets/0xeDF3ce4Dd6725650a8e9398e5C6398D061Fa7955/info.json) [Website](https://vemp.xyz) [Explorer](https://bscscan.com/token/0xeDF3ce4Dd6725650a8e9398e5C6398D061Fa7955)
Tags: defi
Token check error: 
failed to get logo: unsuccessful status code: 404
❌ number of holders not checked: please, check it manually

<span style="padding: 5px; background-color: rgb(32,32,32);"><img src="https://raw.githubusercontent.com/MikeVEMP/assets/master/blockchains/smartchain/assets/0xeDF3ce4Dd6725650a8e9398e5C6398D061Fa7955/logo.png" style="max-width: 64px; border-radius: 48%;" width="48" height="48"/></span>

-----
**Token ERC20 - 0xcFEB09C3c5F0f78aD72166D55f9e6E9A60e96eEC**:
Failed to get info.json content: failed to unmarshal json: invalid character ':' after top-level value (https://raw.githubusercontent.com/MikeVEMP/assets/master/blockchains/ethereum/assets/0xcFEB09C3c5F0f78aD72166D55f9e6E9A60e96eEC/info.json)

_Originally posted by @merge-fee-bot[bot] in https://github.com/trustwallet/assets/issues/24159#issuecomment-1445060936_

**Comment by CustomerTeam001** [comment]
We'd be happy to look into this for you 
kindly file a support ticket below 
https://forms.gle/FhSmn4AznQtZcruX8

**Comment by Tegimufranka9639** [comment]
Merge all account on binance BNB BSC on my main account

**Comment by CustomerTeam001** [comment]
@Tegimufranka9639 We'd be happy to look into this for you 
kindly file a support ticket below 
https://forms.gle/FhSmn4AznQtZcruX8
