### ISSUE TITLE
@trustwallet/wallet-core problem in node.js with the require fs/promises

### ISSUE THREAD

**Issue by ArturLevchuk** [trustwallet/trust-web3-provider#493]
Hi everyone! I have updated trustwallet/wallet-core in my node.js project and ran into a problem with the require fs/promises. I'm using bundle.js generated by webpack. Does anyone have a solution to this problem?
![image_2024-01-18_235234268](https://github.com/trustwallet/trust-web3-provider/assets/123000776/90a3577e-e050-4fec-b6e0-21025625592e)

**Comment by CryptoCindy** [comment]
Hello, have you been able to resolve this issue?
