### ISSUE TITLE
Is there an Android version?I only see the ios version

### ISSUE THREAD

**Issue by cppfuns** [TrustWallet/trust-web3-provider#5]
I am good at Windows C++ desktop development, learn a little bit of Android, I want to refer to the Trust implementation.
waiting for your reply~

**Comment by vikmeup** [comment]
@madcake can we add Android version?

**Comment by vikmeup** [comment]
Implemented

**Comment by dhruvi1kosmos** [comment]
@vikmeup  @madcake  any implementation example for android for genrating ethereum wallet
