### ISSUE TITLE
Don't see executeCallback function

### ISSUE THREAD

**Issue by luannguyenQV** [TrustWallet/trust-web3-provider#51]
_Sorry for my misunderstanding!_
I see in *trust-wallet-ios*, you are using commit: *f4e0ebb1b8fa4812637babe85ef975d116543dfd* - in this commit you have ***executeCallback*** in Trust (provider). But in current version, I don't see this function again. 
So how can I execute callback after I signed a transaction in my wallet?
Hope the helps.
Thanks.

**Comment by luannguyenQV** [comment]
I tried to use:
`webview.evaluateJavaScript(`provider.sendResponse(${data.id}, {'id': ${data.id}, jsonrpc: '2.0', result: ${signed}, error: null })`)`
But it doesn't work.
@hewigovens Can you help?

**Comment by hewigovens** [comment]
checkout this line: https://github.com/TrustWallet/trust-web3-provider/blob/master/Example/TrustWeb3Provider/DAppWebViewController.swift#L116

**Comment by luannguyenQV** [comment]
Yup, thank you. I will try.

**Comment by luannguyenQV** [comment]
Thanks, It worked for me.
