### ISSUE TITLE
[Solana] Pass serialized message as raw field

### ISSUE THREAD

**Issue by JaimeToca** [trustwallet/trust-web3-provider#519]
With the latest changes regarding Solana versioned transaction, raw is not a "serialized message" anymore and can't be signed, therefore it can create a bit of confusion as clients need to:
1) Decode raw transaction
2) Extract message
3) Serialized message
4) Sign message

![Screenshot 2024-04-22 at 17 17 20](https://github.com/trustwallet/trust-web3-provider/assets/11850271/2eb98523-a9c9-481e-83e9-dbfa75677340)

Ideally, clients should receive serialized messages that can directly be signed, so apps can return signatures.

**Comment by Mohammed-yimam** [comment]
[mohammed-yimam-main.zip](https://github.com/trustwallet/trust-web3-provider/files/15110427/mohammed-yimam-main.zip)

**Comment by Mohammed-yimam** [comment]
ጥሩ ነው

**Comment by Mohammed-yimam** [comment]
አመሰግናለሁ ጥሩ ነው

**Comment by y3fers0n** [comment]
Implemented with https://github.com/trustwallet/trust-web3-provider/pull/522
