### ISSUE TITLE
Report bug in TrustWeb3Provider.setConfig

### ISSUE THREAD

**Issue by liweiz** [TrustWallet/trust-web3-provider#52]
https://github.com/TrustWallet/trust-web3-provider/blob/ae735bb046030e671b313de4049947d46c11f658/src/index.js#L33

Line 33 of index.js:

It should be something like:

`this.filterMgr = new FilterMgr(this.rpc);`

current as in ae735bb:

`this.filterMgr = new FilterMgr(config.rpcUrl);`

For _FilterMgr_, a _RPCServer_ instance is required instead of _String_ of a url.

I was trying to make a pull request, but I'm not able to create a new branch for this repo and the repo I forked is used for something else.

Thank you for your work,

Liwei

edit: added direct link to the source code

**Comment by hewigovens** [comment]
Thanks for reporting, we'll fix it soon
