### ISSUE TITLE
More information...

### ISSUE THREAD

**Issue by Alkhatri77** [trustwallet/trust-web3-provider#521]
More information...

This error cropped up after I had a `yarn.lock` conflict. In the middle of a rebase I `rm -rf yarn.lock` and kept `yarn`-ing until the rebase was over.

So it's like this is only happening on a fresh `yarn.lock`.

_Originally posted by @jcreamer898 in https://github.com/yarnpkg/yarn/issues/6152#issuecomment-407819685_

**Comment by Alkhatri77** [comment]
Help my

**Comment by y3fers0n** [comment]
Not related
