### ISSUE TITLE
Why is TrustChain3Provider.isConnected always True?

### ISSUE THREAD

**Issue by liweiz** [TrustWallet/trust-web3-provider#54]
https://github.com/TrustWallet/trust-web3-provider/blob/1284aee71a3f6fb2073624b4fcf533aff9f2b220/src/index.js#L20

It is probably a silly issue for some. But I just can't figure it out myself.

**Comment by kolya182** [comment]
It is simply used to verify if Trust We3 injected 
Example of use:
https://github.com/TrustWallet/dapps-browser/blob/2c72f06c0c379005a549d7f577ae088dc39f8ffb/src/components/systemchecks/ConnectionStatus.js#L12
