### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by shihshi** [TrustWallet/trust-web3-provider#65]
I saw the trust-web3-provider is declared to MIT lincense, but there is one file /src/package.json write down the license is GPL3.0,  so what the License term is correct ?

**Comment by hewigovens** [comment]
Hi, MIT

**Comment by vikmeup** [comment]
https://github.com/TrustWallet/trust-web3-provider/commit/d1878580158cda4009d3259d36664d4bc510a8da
