### ISSUE TITLE
Cannot find function 'executeCallback' when using provider in iOS

### ISSUE THREAD

**Issue by James-Sangalli** [TrustWallet/trust-web3-provider#69]
Hi @hewigovens & @vikmeup ,

I forked this provider here: https://github.com/James-Sangalli/AlphaWallet-web3-provider
Merely changing the naming to map to AlphaWallet rather than trust.

And I implemented the handling in iOS here: https://github.com/AlphaWallet/alpha-wallet-ios/commit/79bed87caf1b39a722a6eeac1da593d35b1cd5c4

Many of the functions like sendAsync are there and things like web3.currentProvider, window.ethereum and web3.currentProvider.isAlphaWallet are all set.

When I go to this website: https://rstormsf.github.io/js-eth-personal-sign-examples/ I am able to trigger prompts for signing but every time a call is supposed to be made back to the device hooks, I get an error stating that there is not executeCallback function in the script. 

Perplexed, I looked at the sample minified file inside the android part of the provider and found that executeCallback was there and that the version built for android differs for the one that is built to the dist folder.

It seems this is working well in trust, so would it be possible to let in some insight about the exact version being used in the podspec and perhaps whether the wkscripts implemented in iOS differ to the ones being implemented here?

If so, we can fix this for other users.

**Comment by hewigovens** [comment]
We don't use `executeCallback` anymore, you should change it here: https://github.com/AlphaWallet/alpha-wallet-ios/blob/master/AlphaWallet/Browser/ViewControllers/BrowserViewController.swift#L147

**Comment by James-Sangalli** [comment]
@hewigovens thanks for that, I am guessing you use postMessage(handler, id, data) now instead?

**Comment by James-Sangalli** [comment]
Solved with sendResponse callback, note that 'this' is not reliable in the provider class.
