### ISSUE TITLE
Legacy eth_signTypedData Never Fires a Callback

### ISSUE THREAD

**Issue by ZitRos** [trustwallet/trust-web3-provider#73]
Hello! Thanks for taking time coming across this issue!

I came here from Trust's iOS app.

Regardless of the standard, it seems that `eth_signTypedData` call **is unresponsive** (neither give a sign popup nor throws an error):

```javascript
      window.web3.currentProvider.sendAsync({
        method: 'eth_signTypedData',
        params: [data, state.currentEthereumAccount.toString()],
        from: state.currentEthereumAccount.toString(),
      }, function (err, result) {
        // It never executes this code
        state.globalInfoMessage = `err ${err}, result: ${result}`;
      });
```

Though if I call `method: "eth_signTypedData100500"` it throws an error.

Platform: Trust for iOS
Live demo: [here](https://zitros.github.io/ethereum-delegated-tx-widget/) (press "Confirm" and see that there are no sign pop-ups, while if you do the same with Metamask it works)

**I understand that `eth_signTypedData` is not a standard yet**; however, **it has to throw an error** at least if you don't support this method or invalid parameters are given.

As a result, I need to code a hack which will suggest another signature standard for the user, instead of just automatically switching to this standard because there are errors detected in `eth_signTypedData`.

Hope to hear any feedback from you. Thank you!

**Comment by ZitRos** [comment]
Just tested this in Android app, and it works there. So its a problem with iOS app.

**Comment by hewigovens** [comment]
Hi, I tried https://zitros.github.io/ethereum-delegated-tx-widget/ and it looks like the data is not valid eip712 data? could you please share an example? Trust iOS only supports `eth_signTypedData_v3`

for a working example in Trust, please refer `sign typed data v3` in https://js-eth-sign.surge.sh

**Comment by ZitRos** [comment]
Hi @hewigovens! Thanks for your quick feedback!

> Trust iOS only supports eth_signTypedData_v3
Right! And once I call `eth_signTypedData` (legacy) with legacy data, I just get silence. I am sure it must throw an error instead.

**Comment by ZitRos** [comment]
Because of this problem, I had to implement a workaround on the application level:

![image](https://user-images.githubusercontent.com/4989256/64020934-80726380-cb3b-11e9-85d8-5a4a3e3f23d7.png)

But by design, if it gets the error, it switches to the next supported standard automatically.

**Comment by hewigovens** [comment]
I totally agree, web3 is a mess, it's so hard to push something

**Comment by ZitRos** [comment]
As for web3, that's right. Do you think this is a web3 bug but not Trust's for iOS?

**Comment by hewigovens** [comment]
We will throw an error for legacy eip712 data, right now it expects v3 data

**Comment by ZitRos** [comment]
> We will throw an error for legacy eip712 data

Awesome, thanks! When can we expect this then?

By the way, somewhen around 6 months ago, Trust supported `eth_signTypedData` which is now "legacy", and it worked great. Is there any possibility you also consider supporting the legacy signing as well? Our token has this implementation hard-coded forever, and it would be awesome if you could leave it, just like legacy `eth_sign`.

**Comment by hewigovens** [comment]
close this in favor of https://github.com/trustwallet/trust-web3-provider/issues/148
