### ISSUE TITLE
IOS vs Android Bug

### ISSUE THREAD

**Issue by EnoRage** [trustwallet/trust-web3-provider#75]
Here you can see bug:

Android:
![2019-08-30 07 09 05](https://user-images.githubusercontent.com/22479658/63992550-10d98580-caf5-11e9-9a1d-16893d4325e8.jpg)
IOS:
![2019-08-30 07 09 21](https://user-images.githubusercontent.com/22479658/63992560-1cc54780-caf5-11e9-9936-aa7611821161.jpg)

According to the docs here:
https://developer.trustwallet.com/trust-provider

Interface of account must be like this:
```
[
  {
    network: number,
    address: string
  }
]
```

However for Android App it is like this:
```
[
  {
    id: number,
    address: string
  }
]
```

Android version: 1.7.030
IOS version: 2.6905 (6905)

**Comment by leoneparise** [comment]
Fixed submitted on Android app: https://github.com/trustwallet/android/pull/1601

**Comment by leoneparise** [comment]
I'm closing this one because I opened another issue (and fix) on Android project: https://github.com/trustwallet/android/issues/1602
