### ISSUE TITLE
invalid json rpc response: ""

### ISSUE THREAD

**Issue by olegabr** [trustwallet/trust-web3-provider#76]
This plugin is used: https://wordpress.org/plugins/ether-and-erc20-tokens-woocommerce-payment-gateway/

It uses old stable web3js lib version 0.20.X

The payment works well on desktop with MetaMask, but on a mobile iOS Trust Wallet it says: `invalid json rpc response: ""`

The site in question: https://www.maningimines.com/

![IMG_0857](https://user-images.githubusercontent.com/2850808/65227585-196d1c80-daf3-11e9-87f3-13ca999f39dc.jpg)

**Comment by olegabr** [comment]
I've tried this site with Trust Wallet on Android and it works fine. only iOS has this issue

**Comment by kolya182** [comment]
Is this happens every-time to on checkout page ?. Did not happen to me.

**Comment by olegabr** [comment]
Yes, client get this error every time she tries to pay with her iphone.

**Comment by hewigovens** [comment]
sorry for late update: I got this error when placing order
![image](https://user-images.githubusercontent.com/360470/65812601-d2221280-e1fb-11e9-8ccf-436ac8aae0fa.png)

**Comment by olegabr** [comment]
looks like infura.io CORS problem. will ask them
