### ISSUE TITLE
Implement eip1102

### ISSUE THREAD

**Issue by dpereskokov** [trustwallet/trust-web3-provider#82]
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1102.md

**Comment by hewigovens** [comment]
This is done actually, we need EIP1193

**Comment by vikmeup** [comment]
@hewigovens from what friend told me `const accounts = await ethereum.send('eth_requestAccounts');` does not work yet, but we still need to support ` ethereum.enable()` too, it's an alias

**Comment by hewigovens** [comment]
yes, should be fixed after we implement 1193
