### ISSUE TITLE
eth_signTypedData generates an invalid signature for uint32 integers on android.

### ISSUE THREAD

**Issue by leroldary** [trustwallet/trust-web3-provider#87]
The android version of Trustwallet generates an invalid signature for uint32 integers.
Example data:
```
{
  types:{
    EIP712Domain:[],
    Test:[
      {name: "test", type: "uint32"}
    ],
  },
  primaryType:"Test",
  domain: {},
  message: {
    test: 0,
  },
}
```
Example (Trust-Wallet eip-712 bug button): https://dicether.github.io/js-eth-personal-sign-examples/

**Comment by hewigovens** [comment]
Thanks for reporting, we're investigating

**Comment by madcake** [comment]
Fixed on android
