### ISSUE TITLE
Undefined is not an object (evaluating 'window.web3.currentProvider.publicConfigStore.on')

### ISSUE THREAD

**Issue by bachlongkocanh** [trustwallet/trust-web3-provider#89]
I have run on some websites with my custom rpc, the error is as follows:
```Undefined is not an object (evaluating 'window.web3.currentProvider.publicConfigStore.on')```.
How to resolve it??
Thank!

**Comment by hewigovens** [comment]
I don’t think we expose this property

**Comment by bachlongkocanh** [comment]
@hewigovens  I resolved this issue. But i have new issue, i don't find `executeCallback` in your source code. How to execute callback action?
