### ISSUE TITLE
eth_signTypedData_v3 on android fails for uint256 values >= 2^255

### ISSUE THREAD

**Issue by hoytech** [trustwallet/trust-web3-provider#92]
I noticed that eth_signTypedData_v3 signatures are incorrectly computed for uint256 values in certain cases. It only appears to affect Trust Wallet on Android. iOS works OK, as does Metamask on all platforms.

Specifically, it seems when the value is >= 2^255 it fails. It should be able to handle values up to the top of the uint256 range (2^256 - 1). Maybe it's treating the value as signed somewhere?

I created a test case available here: https://hoytech.github.io/js-eth-personal-sign-examples/

Just click on the "Trust-Wallet eip-712 bug" button in trust wallet on android and you'll see "Failed to verify..."

Apologies if this is the wrong repo to report this. Please point me to the correct one if so.

Thanks!

**Comment by hewigovens** [comment]
hi, we will implement new provider in android, so this should be fixed in js side

**Comment by hoytech** [comment]
@hewigovens @vikmeup - Thanks for the reply. Can I ask what you mean fixed in the js side? Is it possible to sign messages with a very large uint256 value somehow? Note that this error occurs even when we encode it as a string. See this test-case: https://github.com/hoytech/js-eth-personal-sign-examples/blob/master/index.js#L385-L398

If not, when can we expect the new provider for android? Thanks!

**Comment by hewigovens** [comment]
no ETA yet, Apple doesn't like web3/dapp browser, we're considering if it's worth to support it at all

**Comment by hoytech** [comment]
Thanks for the update. Actually, I am having a problem with Android, not Apple devices. Apple devices seem to work fine for this test-case, it's just Android that fails.

**Comment by vcoolish** [comment]
Fixed on client, will be available in version 1.10.4. 
Can be closed now

**Comment by hoytech** [comment]
Thank you!
